-- Declarative schema (source of truth for `atlas migrate diff`).
--
-- Naming convention: snake_case tables/columns, mapped to camelCase JS via the
-- `postgres.camel` transform passed to `createDb()` (SimplyChords' convention —
-- see docs/roadmap/02-foundation.md Part A step 2 for the decision writeup).
--
-- Reproduces the 6 current Prisma models 1:1 (see prisma/schema.prisma and
-- docs/roadmap/01-architecture.md §5): Experiment, ExperimentOverride,
-- DashboardGrant, AMASession, AMAPromptData, AMAQuestion (+ AMAQuestionState).
--
-- Note: Prisma's `@updatedAt` on AMAQuestion.updatedAt was a Prisma-client-side
-- behavior (set on every client `.update()` call), not a DB trigger. There is no
-- trigger reproducing it here — the route migration (raw SQL, see #128) is
-- responsible for setting `updated_at = now()` explicitly on updates.

CREATE TABLE experiments (
  name        TEXT PRIMARY KEY,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ,
  range_start INTEGER NOT NULL,
  range_end   INTEGER NOT NULL
);

CREATE TABLE experiment_overrides (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id        TEXT NOT NULL,
  experiment_name TEXT NOT NULL REFERENCES experiments (name) ON DELETE CASCADE,

  CONSTRAINT experiment_overrides_guild_id_experiment_name_key UNIQUE (guild_id, experiment_name)
);

CREATE INDEX experiment_overrides_experiment_name_idx ON experiment_overrides (experiment_name);

CREATE TABLE dashboard_grants (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id       TEXT NOT NULL,
  user_id        TEXT NOT NULL,
  created_by_id  TEXT NOT NULL,

  CONSTRAINT dashboard_grants_guild_id_user_id_key UNIQUE (guild_id, user_id)
);

CREATE TABLE ama_sessions (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id                 TEXT NOT NULL,
  mod_queue_id             TEXT,
  flagged_queue_id         TEXT,
  guest_queue_id           TEXT,
  title                    TEXT NOT NULL,
  answers_channel_id       TEXT NOT NULL,
  prompt_channel_id        TEXT NOT NULL,
  allowed_question_uploads INTEGER NOT NULL DEFAULT 2,
  ended                    BOOLEAN NOT NULL DEFAULT false,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE ama_prompt_data (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ama_id            INTEGER NOT NULL UNIQUE REFERENCES ama_sessions (id) ON DELETE CASCADE,
  prompt_message_id TEXT NOT NULL UNIQUE,
  prompt_json_data  TEXT NOT NULL
);

CREATE TYPE ama_question_state AS ENUM (
  'PENDING_MOD_REVIEW',
  'PENDING_GUEST_REVIEW',
  'FLAGGED',
  'APPROVED',
  'DENIED'
);

CREATE TABLE ama_questions (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ama_id                   INTEGER NOT NULL REFERENCES ama_sessions (id) ON DELETE CASCADE,
  author_id                TEXT NOT NULL,
  state                    ama_question_state NOT NULL DEFAULT 'PENDING_MOD_REVIEW',
  content                  TEXT NOT NULL,
  mod_queue_message_id     TEXT,
  guest_queue_message_id   TEXT,
  flagged_queue_message_id TEXT,
  answers_message_id       TEXT,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ama_questions_ama_id_idx ON ama_questions (ama_id);
