name: chatsift-next

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: 'chatsift'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'chatsift'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - ./.env.public
      - ./.env.private
    ports:
      - 127.0.0.1:${LOCAL_DATABASE_PORT}:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U chatsift']
      interval: 10s
      timeout: 5s

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOZZLE_ENABLE_ACTIONS: true
    ports:
      - 127.0.0.1:8080:8080

  redis:
    image: redis:6-alpine
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 10s
      timeout: 5s

  discord-proxy:
    image: chatsift/chatsift-next:automoderator-discord-proxy
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env.public
      - ./.env.private
    command: ['node', '--enable-source-maps', './services/discord-proxy/dist/index.js']
    volumes:
      - ./logs-archive:/var/chatsift-logs

  gateway:
    image: chatsift/chatsift-next:automoderator-gateway
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env.public
      - ./.env.private
    command: ['node', '--enable-source-maps', './services/gateway/dist/index.js']
    volumes:
      - ./logs-archive:/var/chatsift-logs

  interactions:
    image: chatsift/chatsift-next:automoderator-interactions
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env.public
      - ./.env.private
    command: ['node', '--enable-source-maps', './services/interactions/dist/index.js']
    volumes:
      - ./logs-archive:/var/chatsift-logs

  observer:
    image: chatsift/chatsift-next:automoderator-observer
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env.public
      - ./.env.private
    command: ['node', '--enable-source-maps', './services/observer/dist/index.js']
    volumes:
      - ./logs-archive:/var/chatsift-logs

volumes:
  # TODO: Rename at some point
  postgres-data:
    name: 'chatsift-next-postgres-data'
