import { defineConfig } from 'vitest/config';

export default defineConfig({
	test: {
		exclude: ['**/node_modules', '**/dist', '.idea', '.git', '.cache'],
		passWithNoTests: true,
		typecheck: {
			enabled: true,
			include: ['**/__tests__/types.test.ts'],
			tsconfig: 'tsconfig.json',
		},
		coverage: {
			enabled: true,
			reporter: ['text', 'lcov', 'clover'],
			// Without this, vitest only reports on files some test happened to *import* -- a file nothing
			// imports is absent from the report entirely rather than sitting at 0%, which made the numbers
			// describe the test suite instead of the codebase (37 files reported out of 228 real ones).
			include: ['packages/*/*/src/**/*.ts', 'services/*/src/**/*.ts'],
			exclude: [
				'**/dist',
				'**/__tests__',
				'**/__mocks__',
				'**/coverage',
				'**/tsup.config.ts',
				'**/vitest.config.ts',
				'**/.next',
				'eslint.config.js',
				'.yarn',
				'apps/website',
				// Everything below is deliberately *not* unit tested (#339), so it's excluded rather than
				// left to sit at 0% forever and dilute the number into meaninglessness:
				'packages/private/db/src/generated/**', // kanel output, type-only, regenerated by `yarn db:gen`
				'packages/private/db/src/scripts/**', // one-shot migration scripts, verified against scratch DBs instead
				'**/src/bin.ts', // process entrypoints
				'services/*/src/index.ts', // api: a pure re-export barrel; the bots: gateway event wiring
			],
		},
	},
});
