import type { Logger } from '@chatsift/backend-core';
import { getContext } from '@chatsift/backend-core';
import type { Categories, Threads } from '@chatsift/db';
import type { APIEmbed, APIGuildMember, APIUser } from '@discordjs/core';
import { CDNRoutes, ImageFormat, RouteBases } from '@discordjs/core';
import { getAnonReplyLabelTemplate, getGuildInfo } from './guild.js';
import { templateDataFromMember, templateGuildName, templateString } from './templateString.js';
import {
	countPastThreadsForUser,
	incrementLocalMessageId,
	insertThreadMessage,
	isRecordingEnabled,
	MAX_THREAD_AUTO_ARCHIVE_DURATION_MINUTES,
} from './threads.js';

/**
 * Used for both the ticket-opening info embed and the greeting, distinct from the green/blurple
 * relay colors (`lib/relay.ts`) so "informational" posts read differently from an actual
 * back-and-forth message.
 */
const NOT_QUITE_BLACK = 0x23272a;

/**
 * Discord's subtext markdown (`-#`) keeps this from competing visually with the actual "who is this"
 * info embed right below it -- it only needs to register once, not draw the eye every time mods scroll
 * past the top of the thread.
 */
const RECORDING_NOTICE_CONTENT = "-# ⚠️ This ticket's messages are being recorded and viewable on the dashboard.";

/**
 * Discord's snowflake epoch (2015-01-01T00:00:00.000Z), used to derive account-creation date.
 */
const DISCORD_EPOCH = 1_420_070_400_000n;

function snowflakeCreatedAt(id: string): Date {
	return new Date(Number((BigInt(id) >> 22n) + DISCORD_EPOCH));
}

function discordDate(date: Date): string {
	return `<t:${Math.floor(date.getTime() / 1_000)}:D>`;
}

/**
 * `finishTicketCreation` only ever runs from `index.ts`'s message-driven path (the `user`-less
 * `APIGuildMemberNoUser` the gateway attaches to `MESSAGE_CREATE`), never directly from an
 * interaction — narrowed to just the fields actually read here so that satisfies it.
 */
type MemberLike = Pick<APIGuildMember, 'avatar' | 'joined_at' | 'nick' | 'roles'>;

export interface FinishTicketCreationOptions {
	alertRoleId: string | null;
	category: Categories | null;
	createdById: string;
	guildId: string;
	logger: Logger;
	member: MemberLike | undefined;
	modForumId: string;
	/**
	 * How this ticket was opened -- `'panel'` from `index.ts#handleFirstMessage`, `'dm'` from
	 * `lib/dmTicket.ts` (#216, P4). Stored on `threads.origin`; see that column's doc comment in
	 * schema.sql for what each caller must never do to `userChannelId` as a result.
	 */
	origin: Threads['origin'];
	user: APIUser;
	/**
	 * The Discord channel the user's side of the conversation happens in -- a private thread this bot
	 * created (`origin: 'panel'`) or the opener's DM channel (`origin: 'dm'`). See `threads.user_channel_id`'s
	 * doc comment in schema.sql for why this is deliberately not called "...threadId".
	 */
	userChannelId: string;
}

/**
 * Called once from `index.ts`'s `handleFirstMessage` (panel flow) or `lib/dmTicket.ts` (DM mode,
 * #216 P4), once the user's opening message is known -- the category (if any) was already resolved
 * before this point (`categorySelect.ts`/`dmTicket.ts`'s category prompt), so this only ever has one
 * job left: open the mod-forum thread (tagged per category, if configured), insert the `threads` row,
 * and post the category's greeting (falling back to the guild default) back into the user's channel.
 * The opening embed's field set (account age, join date, past tickets, roles) intentionally skips a
 * full guild-roles fetch just to sort the roles by position — not worth the extra API call for a
 * cosmetic ordering.
 */
export async function finishTicketCreation({
	alertRoleId,
	category,
	createdById,
	guildId,
	logger,
	member,
	modForumId,
	origin,
	user,
	userChannelId,
}: FinishTicketCreationOptions): Promise<Threads> {
	const displayName = member?.nick ?? user.global_name ?? user.username;
	const avatarURL = member?.avatar
		? `${RouteBases.cdn}${CDNRoutes.guildMemberAvatar(guildId, user.id, member.avatar, ImageFormat.PNG)}`
		: user.avatar
			? `${RouteBases.cdn}${CDNRoutes.userAvatar(user.id, user.avatar, ImageFormat.PNG)}`
			: undefined;

	const pastTicketCount = await countPastThreadsForUser(guildId, user.id);
	const roles = member?.roles.length ? member.roles.map((roleId) => `<@&${roleId}>`).join(', ') : 'none';
	const recording = await isRecordingEnabled(guildId);

	// Reserved *before* the forum thread even exists so the ticket number can be baked into its name from
	// the start -- renaming it after the fact via `channels.edit` works, but Discord posts an unhideable
	// "changed the post title" system message every time, which is worse than the problem it solves. A
	// gap in the sequence if ticket creation fails after this point (rare, and already handled below by
	// deleting the orphaned Discord thread) is a perfectly normal cost of a `GENERATED BY DEFAULT AS
	// IDENTITY` column -- nothing here depends on `threads.id` having no gaps.
	const [{ nextThreadId }] = await getContext().db<[{ nextThreadId: string }]>`
		SELECT nextval(pg_get_serial_sequence('threads', 'id')) AS next_thread_id
	`;
	const reservedThreadId = Number(nextThreadId) as Threads['id'];

	// Only worth linking when recording is on -- the dashboard search results a mod would land on show
	// recorded content, so following the link with recording off would just be a list of "not recorded"
	// placeholders.
	const pastTicketsValue = recording
		? `[${pastTicketCount}](${getContext().FRONTEND_URL}/dashboard/${guildId}/modmail/threads?search=${user.id}&include_closed=true)`
		: String(pastTicketCount);

	const openingEmbedFields = [
		{ name: 'Account Created', value: discordDate(snowflakeCreatedAt(user.id)), inline: true },
		...(member?.joined_at
			? [{ name: 'Joined Server', value: discordDate(new Date(member.joined_at)), inline: true }]
			: []),
		{ name: 'Past Tickets', value: pastTicketsValue, inline: true },
		...(category ? [{ name: 'Category', value: category.name, inline: true }] : []),
		{ name: 'Opened By', value: `<@${createdById}>`, inline: true },
		{ name: 'Roles', value: roles, inline: true },
	];

	const openingEmbed: APIEmbed = {
		color: NOT_QUITE_BLACK,
		author: avatarURL ? { name: displayName, icon_url: avatarURL } : { name: displayName },
		footer: { text: `${user.username} (${user.id})` },
		fields: openingEmbedFields,
		timestamp: new Date().toISOString(),
	};

	// When recording is on, the recording notice has to be the thread's actual starter message (Discord
	// bakes whatever's passed to `message` here in as the very first post, nothing can be inserted before
	// it after the fact) -- the opening info embed and alert-role ping move to a follow-up `createMessage`
	// below instead, once a `threads.id` exists to link back to. When recording is off there's no notice
	// to lead with, so the embed goes right back to being the starter message like before.
	const modThread = await getContext().service.client.api.channels.createForumThread(modForumId, {
		name: `Thread #${reservedThreadId} - ${displayName}`.slice(0, 100),
		applied_tags: category?.forumTagId ? [category.forumTagId] : undefined,
		auto_archive_duration: MAX_THREAD_AUTO_ARCHIVE_DURATION_MINUTES,
		message: recording
			? { content: RECORDING_NOTICE_CONTENT }
			: {
					// Plain content, not an embed field — embeds never trigger a ping, and this is the one
					// place a new ticket should actually notify the configured alert role.
					...(alertRoleId ? { content: `<@&${alertRoleId}>` } : {}),
					embeds: [openingEmbed],
				},
	});

	// If the INSERT fails outright or somehow returns no row, the forum thread above is already live on
	// Discord's side with nothing in our DB pointing at it — clean that up rather than leaving an
	// orphaned thread a mod would see but that no `/reply` command could ever resolve back to a ticket.
	let thread: Threads | undefined;
	try {
		[thread] = await getContext().db<Threads[]>`
			INSERT INTO threads (id, guild_id, mod_thread_id, user_id, created_by_id, category_id, user_channel_id, origin)
			VALUES (
				${reservedThreadId}, ${guildId}, ${modThread.id}, ${user.id}, ${createdById}, ${category?.id ?? null},
				${userChannelId}, ${origin}
			)
			RETURNING *
		`;

		if (!thread) {
			throw new Error(`Failed to insert thread row for mod thread ${modThread.id}`);
		}
	} catch (error) {
		logger.error(
			{ err: error, modThreadId: modThread.id },
			'Failed to persist new ticket, deleting orphaned mod thread',
		);
		await getContext().service.client.api.channels.delete(modThread.id, {
			reason: 'Rolling back failed ticket creation',
		});
		throw error;
	}

	if (recording) {
		// Deferred from the forum-thread-creation call above (see its own comment) now that `thread.id`
		// exists to link back to — carries the alert-role ping the recording notice itself didn't, so a
		// new ticket still notifies exactly like it would have without recording on. Best-effort: the ticket
		// itself is already fully created and persisted by this point, so a Discord hiccup posting this one
		// follow-up embed shouldn't fail ticket creation outright and block the relay/greeting flow that
		// still needs to run in `index.ts#handleFirstMessage` right after this returns.
		try {
			const dashboardUrl = `${getContext().FRONTEND_URL}/dashboard/${guildId}/modmail/threads/${thread.id}`;
			await getContext().service.client.api.channels.createMessage(modThread.id, {
				...(alertRoleId ? { content: `<@&${alertRoleId}>` } : {}),
				embeds: [
					{
						...openingEmbed,
						fields: [
							...openingEmbedFields,
							{ name: 'Dashboard', value: `[View in dash](${dashboardUrl})`, inline: true },
						],
					},
				],
			});
		} catch (error) {
			logger.warn({ err: error, threadId: thread.id }, 'Failed to post the opening info embed to the mod thread');
		}
	}

	logger.info({ threadId: thread.id, modThreadId: modThread.id, userChannelId }, 'Opened new modmail ticket');

	return thread;
}

export interface SendGreetingOptions {
	category: Categories | null;
	defaultGreetingMessage: string | null;
	guildId: string;
	member: MemberLike | undefined;
	modThreadId: string;
	threadId: Threads['id'];
	user: APIUser;
	userChannelId: string;
}

/**
 * Deliberately not part of `finishTicketCreation` — `index.ts`'s `handleFirstMessage` relays the
 * user's own first message to the mod thread itself right after creating it, and needs to sequence
 * this against that relay call depending on `guild_settings.greetingBeforeOpener` (default `false`:
 * greeting lands *after* the relay, so the mod-side thread reads opening info embed, then the user's
 * actual message, then the bot's greeting reply to it — set `true` to flip that order). Posting the
 * greeting from inside `finishTicketCreation` would hardcode one order with no way for the caller to
 * flip it.
 */
export async function sendGreeting({
	category,
	defaultGreetingMessage,
	guildId,
	member,
	modThreadId,
	threadId,
	user,
	userChannelId,
}: SendGreetingOptions): Promise<void> {
	const greeting = category?.greetingMessage ?? defaultGreetingMessage;
	if (!greeting || !member) {
		return;
	}

	const [guild, labelTemplate] = await Promise.all([getGuildInfo(guildId), getAnonReplyLabelTemplate(guildId)]);
	const label = templateGuildName(labelTemplate, guild.name);

	// Same divergence from ChatSift/ModMail as anon replies (lib/relay.ts): the "\{guildName\} Team" identity
	// lives in the footer, not the author slot — an author line here would just duplicate it.
	const resolvedContent = templateString(greeting, templateDataFromMember(guild.name, member, user));
	const greetingEmbed: APIEmbed = {
		color: NOT_QUITE_BLACK,
		description: resolvedContent,
		footer: guild.iconURL ? { text: label, icon_url: guild.iconURL } : { text: label },
	};

	// Posted into both threads — mods should see the automated greeting land in the mod-forum
	// thread too, the same way a staff-sent reply's log copy does, instead of it only being
	// visible from the user's side.
	const [userMessage, modMessage] = await Promise.all([
		getContext().service.client.api.channels.createMessage(userChannelId, { embeds: [greetingEmbed] }),
		getContext().service.client.api.channels.createMessage(modThreadId, { embeds: [greetingEmbed] }),
	]);

	// Recorded the same way a staff reply is (Phase 3, #261) -- `is_system` distinguishes it from a real
	// staff/user message on read, since there's no actual staff actor for a `staffId` to name (see
	// schema.sql's own doc comment). Only inserted when recording is enabled at all, same as internal
	// mod-chatter -- an unrecorded system row would carry zero information.
	if (await isRecordingEnabled(guildId)) {
		const localThreadMessageId = await incrementLocalMessageId(threadId);
		await insertThreadMessage({
			anon: false,
			content: {
				attachments: [],
				isForwarded: false,
				repliedToThreadMessageId: null,
				stickers: [],
				text: resolvedContent,
			},
			guildId,
			guildMessageId: modMessage.id,
			isSystem: true,
			localThreadMessageId,
			staffId: null,
			threadId,
			userId: user.id,
			userMessageId: userMessage.id,
		});
	}
}
