-- Add value to enum type: "ama_question_state"
ALTER TYPE "ama_question_state" ADD VALUE 'ASKED';
-- Modify "ama_questions" table
ALTER TABLE "ama_questions" ADD COLUMN "answer_content" text NULL, ADD COLUMN "answer_image_url" text NULL, ADD COLUMN "answered_by_id" text NULL, ADD COLUMN "answered_at" timestamptz NULL;
-- Create "ama_question_askers" table
CREATE TABLE "ama_question_askers" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "question_id" integer NOT NULL,
  "author_id" text NOT NULL,
  "merged_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "ama_question_askers_question_id_author_id_key" UNIQUE ("question_id", "author_id"),
  CONSTRAINT "ama_question_askers_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "ama_questions" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "ama_question_askers_question_id_idx" to table: "ama_question_askers"
CREATE INDEX "ama_question_askers_question_id_idx" ON "ama_question_askers" ("question_id");
-- Modify "ama_sessions" table
ALTER TABLE "ama_sessions" ADD COLUMN "prepared_answers_enabled" boolean NOT NULL DEFAULT false, ADD COLUMN "mod_review_enabled" boolean NOT NULL DEFAULT false, ADD COLUMN "guest_review_enabled" boolean NOT NULL DEFAULT false, ADD COLUMN "share_token" text NULL;
-- Backfill existing rows: a queue that already had a channel counts as "enabled" (preserves current
-- behavior exactly -- see schema.sql's comment on these columns), and every existing AMA gets a
-- generated share_token so the public answers page works retroactively too.
UPDATE "ama_sessions" SET
  "mod_review_enabled" = ("mod_queue_id" IS NOT NULL),
  "guest_review_enabled" = ("guest_queue_id" IS NOT NULL),
  "share_token" = md5(random()::text || clock_timestamp()::text || id::text) || md5(random()::text || id::text);
ALTER TABLE "ama_sessions" ADD CONSTRAINT "ama_sessions_guest_review_enabled_check" CHECK (guest_review_enabled OR (guest_queue_id IS NULL)), ADD CONSTRAINT "ama_sessions_mod_review_enabled_check" CHECK (mod_review_enabled OR (mod_queue_id IS NULL)), ADD CONSTRAINT "ama_sessions_share_token_key" UNIQUE ("share_token");
-- Create "ama_question_tags" table
CREATE TABLE "ama_question_tags" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "ama_id" integer NOT NULL,
  "name" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "ama_question_tags_ama_id_name_key" UNIQUE ("ama_id", "name"),
  CONSTRAINT "ama_question_tags_ama_id_fkey" FOREIGN KEY ("ama_id") REFERENCES "ama_sessions" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "ama_question_tags_ama_id_idx" to table: "ama_question_tags"
CREATE INDEX "ama_question_tags_ama_id_idx" ON "ama_question_tags" ("ama_id");
-- Create "ama_question_tag_assignments" table
CREATE TABLE "ama_question_tag_assignments" (
  "question_id" integer NOT NULL,
  "tag_id" integer NOT NULL,
  PRIMARY KEY ("question_id", "tag_id"),
  CONSTRAINT "ama_question_tag_assignments_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "ama_questions" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "ama_question_tag_assignments_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "ama_question_tags" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "ama_question_tag_assignments_tag_id_idx" to table: "ama_question_tag_assignments"
CREATE INDEX "ama_question_tag_assignments_tag_id_idx" ON "ama_question_tag_assignments" ("tag_id");
