-- Create enum type "automoderator_case_action"
CREATE TYPE "automoderator_case_action" AS ENUM ('WARN', 'MUTE', 'UNMUTE', 'KICK', 'SOFTBAN', 'BAN', 'UNBAN');
-- Create enum type "automoderator_log_type"
CREATE TYPE "automoderator_log_type" AS ENUM ('MOD', 'FILTER', 'MESSAGE', 'USER');
-- Modify "automoderator_guild_settings" table
ALTER TABLE "automoderator_guild_settings" ADD COLUMN "last_case_id" integer NOT NULL DEFAULT 0;
-- Create "automoderator_cases" table
CREATE TABLE "automoderator_cases" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guild_id" text NOT NULL,
  "case_id" integer NOT NULL,
  "ref_id" integer NULL,
  "target_id" text NOT NULL,
  "target_tag" text NOT NULL,
  "mod_id" text NULL,
  "mod_tag" text NULL,
  "action_type" "automoderator_case_action" NOT NULL,
  "reason" text NULL,
  "expires_at" timestamptz NULL,
  "pardoned_by" text NULL,
  "log_message_id" text NULL,
  "dry_run" boolean NOT NULL DEFAULT false,
  "idempotency_key" text NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "automoderator_cases_guild_id_case_id_key" UNIQUE ("guild_id", "case_id")
);
-- Create index "automoderator_cases_guild_id_id_idx" to table: "automoderator_cases"
CREATE INDEX "automoderator_cases_guild_id_id_idx" ON "automoderator_cases" ("guild_id", "id" DESC);
-- Create index "automoderator_cases_guild_id_idempotency_key_idx" to table: "automoderator_cases"
CREATE UNIQUE INDEX "automoderator_cases_guild_id_idempotency_key_idx" ON "automoderator_cases" ("guild_id", "idempotency_key") WHERE (idempotency_key IS NOT NULL);
-- Create index "automoderator_cases_guild_id_target_id_idx" to table: "automoderator_cases"
CREATE INDEX "automoderator_cases_guild_id_target_id_idx" ON "automoderator_cases" ("guild_id", "target_id", "id" DESC);
-- Create "automoderator_log_webhooks" table
CREATE TABLE "automoderator_log_webhooks" (
  "guild_id" text NOT NULL,
  "log_type" "automoderator_log_type" NOT NULL,
  "channel_id" text NOT NULL,
  "webhook_id" text NOT NULL,
  "webhook_token" text NOT NULL,
  "thread_id" text NULL,
  PRIMARY KEY ("guild_id", "log_type")
);
