-- Create "automoderator_report_prompts" table
CREATE TABLE "automoderator_report_prompts" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guild_id" text NOT NULL,
  "channel_id" text NOT NULL,
  "message_id" text NOT NULL,
  "prompt_json_data" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "automoderator_report_prompts_message_id_key" UNIQUE ("message_id")
);
-- Create index "automoderator_report_prompts_guild_id_idx" to table: "automoderator_report_prompts"
CREATE INDEX "automoderator_report_prompts_guild_id_idx" ON "automoderator_report_prompts" ("guild_id");
