-- Modify "thread_messages" table
ALTER TABLE "thread_messages" ADD COLUMN "deleted_at" timestamptz NULL;
-- Create "thread_message_content_edits" table
CREATE TABLE "thread_message_content_edits" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "thread_message_id" integer NOT NULL,
  "edited_at" timestamptz NOT NULL DEFAULT now(),
  "old_content" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "thread_message_content_edits_thread_message_id_fkey" FOREIGN KEY ("thread_message_id") REFERENCES "thread_message_content" ("thread_message_id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "thread_message_content_edits_thread_message_id_idx" to table: "thread_message_content_edits"
CREATE INDEX "thread_message_content_edits_thread_message_id_idx" ON "thread_message_content_edits" ("thread_message_id");
