-- Create enum type "appeal_kind"
CREATE TYPE "appeal_kind" AS ENUM ('BAN', 'TIMEOUT');
-- Create enum type "appeal_status"
CREATE TYPE "appeal_status" AS ENUM ('PENDING', 'NEEDS_MORE_INFO', 'APPROVED', 'DENIED', 'WITHDRAWN');
-- Create enum type "appeal_event_kind"
CREATE TYPE "appeal_event_kind" AS ENUM ('SUBMITTED', 'INFO_REQUESTED', 'INFO_PROVIDED', 'APPROVED', 'DENIED', 'WITHDRAWN', 'NOTE');
-- Create "appeal_ban_checks" table
CREATE TABLE "appeal_ban_checks" (
  "user_id" text NOT NULL,
  "guild_id" text NOT NULL,
  "banned" boolean NOT NULL,
  "ban_reason" text NULL,
  "checked_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "appeal_ban_checks_user_id_guild_id_key" UNIQUE ("user_id", "guild_id")
);
-- Create "appeal_questions" table
CREATE TABLE "appeal_questions" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guild_id" text NOT NULL,
  "position" integer NOT NULL,
  "prompt" text NOT NULL,
  "required" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "appeal_questions_position_check" CHECK ("position" >= 0)
);
-- Create index "appeal_questions_guild_id_position_idx" to table: "appeal_questions"
CREATE INDEX "appeal_questions_guild_id_position_idx" ON "appeal_questions" ("guild_id", "position");
-- Create "appeal_user_state" table
CREATE TABLE "appeal_user_state" (
  "user_id" text NOT NULL,
  "dm_reachable" boolean NULL,
  "dm_checked_at" timestamptz NULL,
  "granted_guilds_join" boolean NOT NULL DEFAULT false,
  "refresh_token" text NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("user_id")
);
-- Create "appeals" table
CREATE TABLE "appeals" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guild_id" text NOT NULL,
  "user_id" text NOT NULL,
  "kind" "appeal_kind" NOT NULL,
  "status" "appeal_status" NOT NULL DEFAULT 'PENDING',
  "silent" boolean NOT NULL DEFAULT false,
  "reason_snapshot" text NULL,
  "mod_message_id" text NULL,
  "mod_thread_id" text NULL,
  "decided_at" timestamptz NULL,
  "decided_by_id" text NULL,
  "decision_reason" text NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "appeals_decision_check" CHECK (
CASE status
    WHEN 'PENDING'::appeal_status THEN ((decided_at IS NULL) AND (decided_by_id IS NULL) AND (decision_reason IS NULL))
    WHEN 'NEEDS_MORE_INFO'::appeal_status THEN ((decided_at IS NULL) AND (decided_by_id IS NULL) AND (decision_reason IS NULL))
    WHEN 'APPROVED'::appeal_status THEN ((decided_at IS NOT NULL) AND (decided_by_id IS NOT NULL))
    WHEN 'DENIED'::appeal_status THEN ((decided_at IS NOT NULL) AND (decided_by_id IS NOT NULL))
    WHEN 'WITHDRAWN'::appeal_status THEN ((decided_at IS NOT NULL) AND (decided_by_id IS NULL))
    ELSE false
END),
  CONSTRAINT "appeals_silent_check" CHECK ((NOT silent) OR (status = 'DENIED'::appeal_status))
);
-- Create index "appeals_guild_id_status_id_idx" to table: "appeals"
CREATE INDEX "appeals_guild_id_status_id_idx" ON "appeals" ("guild_id", "status", "id" DESC);
-- Create index "appeals_open_per_user_idx" to table: "appeals"
CREATE UNIQUE INDEX "appeals_open_per_user_idx" ON "appeals" ("guild_id", "user_id", "kind") WHERE (status = ANY (ARRAY['PENDING'::appeal_status, 'NEEDS_MORE_INFO'::appeal_status]));
-- Create index "appeals_user_id_id_idx" to table: "appeals"
CREATE INDEX "appeals_user_id_id_idx" ON "appeals" ("user_id", "id" DESC);
-- Create "appeals_settings" table
CREATE TABLE "appeals_settings" (
  "guild_id" text NOT NULL,
  "mod_channel_id" text NOT NULL,
  "cooldown_days" integer NOT NULL DEFAULT 30,
  "max_appeals" integer NULL,
  "auto_rejoin" boolean NOT NULL DEFAULT false,
  "allow_timeout_appeals" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("guild_id"),
  CONSTRAINT "appeals_settings_cooldown_days_check" CHECK ((cooldown_days >= 0) AND (cooldown_days <= 365)),
  CONSTRAINT "appeals_settings_max_appeals_check" CHECK ((max_appeals IS NULL) OR ((max_appeals >= 1) AND (max_appeals <= 10)))
);
-- Create "unappealable_patterns" table
CREATE TABLE "unappealable_patterns" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guild_id" text NOT NULL,
  "pattern" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "unappealable_patterns_guild_id_pattern_key" UNIQUE ("guild_id", "pattern")
);
-- Create "unappealable_users" table
CREATE TABLE "unappealable_users" (
  "guild_id" text NOT NULL,
  "user_id" text NOT NULL,
  "reason" text NULL,
  "created_by_id" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("guild_id", "user_id")
);
-- Create "appeal_answers" table
CREATE TABLE "appeal_answers" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "appeal_id" integer NOT NULL,
  "position" integer NOT NULL,
  "prompt_snapshot" text NOT NULL,
  "answer" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "appeal_answers_appeal_id_position_key" UNIQUE ("appeal_id", "position"),
  CONSTRAINT "appeal_answers_appeal_id_fkey" FOREIGN KEY ("appeal_id") REFERENCES "appeals" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "appeal_events" table
CREATE TABLE "appeal_events" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "appeal_id" integer NOT NULL,
  "kind" "appeal_event_kind" NOT NULL,
  "actor_id" text NULL,
  "body" text NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "appeal_events_appeal_id_fkey" FOREIGN KEY ("appeal_id") REFERENCES "appeals" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "appeal_events_appeal_id_id_idx" to table: "appeal_events"
CREATE INDEX "appeal_events_appeal_id_id_idx" ON "appeal_events" ("appeal_id", "id");
