-- Create enum type "automoderator_report_state"
CREATE TYPE "automoderator_report_state" AS ENUM ('OPEN', 'DISMISSED', 'ACTIONED');
-- Modify "automoderator_guild_settings" table
ALTER TABLE "automoderator_guild_settings" ADD COLUMN "reports_channel_id" text NULL;
-- Create "automoderator_report_presets" table
CREATE TABLE "automoderator_report_presets" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guild_id" text NOT NULL,
  "reason" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "automoderator_report_presets_guild_id_reason_key" UNIQUE ("guild_id", "reason")
);
-- Create index "automoderator_report_presets_guild_id_idx" to table: "automoderator_report_presets"
CREATE INDEX "automoderator_report_presets_guild_id_idx" ON "automoderator_report_presets" ("guild_id", "id");
-- Create "automoderator_reports" table
CREATE TABLE "automoderator_reports" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guild_id" text NOT NULL,
  "target_id" text NOT NULL,
  "target_tag" text NOT NULL,
  "message_id" text NULL,
  "channel_id" text NULL,
  "message_content" text NULL,
  "message_image_url" text NULL,
  "state" "automoderator_report_state" NOT NULL DEFAULT 'OPEN',
  "resolved_by" text NULL,
  "resolved_at" timestamptz NULL,
  "case_id" integer NULL,
  "card_channel_id" text NULL,
  "card_message_id" text NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
-- Create index "automoderator_reports_guild_id_id_idx" to table: "automoderator_reports"
CREATE INDEX "automoderator_reports_guild_id_id_idx" ON "automoderator_reports" ("guild_id", "id" DESC);
-- Create index "automoderator_reports_guild_id_message_id_idx" to table: "automoderator_reports"
CREATE UNIQUE INDEX "automoderator_reports_guild_id_message_id_idx" ON "automoderator_reports" ("guild_id", "message_id") WHERE (message_id IS NOT NULL);
-- Create index "automoderator_reports_guild_id_target_id_idx" to table: "automoderator_reports"
CREATE INDEX "automoderator_reports_guild_id_target_id_idx" ON "automoderator_reports" ("guild_id", "target_id", "id" DESC);
-- Create index "automoderator_reports_guild_id_target_id_open_idx" to table: "automoderator_reports"
CREATE UNIQUE INDEX "automoderator_reports_guild_id_target_id_open_idx" ON "automoderator_reports" ("guild_id", "target_id") WHERE ((message_id IS NULL) AND (state = 'OPEN'::automoderator_report_state));
-- Create "automoderator_reporters" table
CREATE TABLE "automoderator_reporters" (
  "report_id" integer NOT NULL,
  "reporter_id" text NOT NULL,
  "reporter_tag" text NOT NULL,
  "reason" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("report_id", "reporter_id"),
  CONSTRAINT "automoderator_reporters_report_id_fkey" FOREIGN KEY ("report_id") REFERENCES "automoderator_reports" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
