-- Create enum type "automoderator_banword_action"
CREATE TYPE "automoderator_banword_action" AS ENUM ('WARN', 'MUTE', 'KICK', 'BAN', 'REPORT');
-- Create "automoderator_banword_policies" table
CREATE TABLE "automoderator_banword_policies" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guild_id" text NOT NULL,
  "rule_id" text NOT NULL,
  "keyword" text NULL,
  "action_type" "automoderator_banword_action" NOT NULL,
  "duration_seconds" integer NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "automoderator_banword_policies_key" UNIQUE NULLS NOT DISTINCT ("guild_id", "rule_id", "keyword"),
  CONSTRAINT "automoderator_banword_policies_duration_check" CHECK (
CASE action_type
    WHEN 'MUTE'::automoderator_banword_action THEN (duration_seconds >= 1)
    WHEN 'BAN'::automoderator_banword_action THEN ((duration_seconds IS NULL) OR (duration_seconds >= 1))
    ELSE (duration_seconds IS NULL)
END)
);
-- Create index "automoderator_banword_policies_guild_id_rule_id_idx" to table: "automoderator_banword_policies"
CREATE INDEX "automoderator_banword_policies_guild_id_rule_id_idx" ON "automoderator_banword_policies" ("guild_id", "rule_id");
-- Create "automoderator_bypass_roles" table
CREATE TABLE "automoderator_bypass_roles" (
  "guild_id" text NOT NULL,
  "role_id" text NOT NULL,
  PRIMARY KEY ("guild_id", "role_id")
);
