-- Create "blocks" table
CREATE TABLE "blocks" (
  "user_id" text NOT NULL,
  "guild_id" text NOT NULL,
  "expires_at" timestamptz NULL,
  PRIMARY KEY ("user_id", "guild_id")
);
-- Create "categories" table
CREATE TABLE "categories" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guild_id" text NOT NULL,
  "name" text NOT NULL,
  "emoji" text NULL,
  "description" text NULL,
  "greeting_message" text NULL,
  "forum_tag_id" text NULL,
  "sort_order" integer NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "categories_guild_id_name_key" UNIQUE ("guild_id", "name")
);
-- Create index "categories_guild_id_idx" to table: "categories"
CREATE INDEX "categories_guild_id_idx" ON "categories" ("guild_id");
-- Create "guild_settings" table
CREATE TABLE "guild_settings" (
  "guild_id" text NOT NULL,
  "mod_forum_id" text NULL,
  "default_greeting_message" text NULL,
  "farewell_message" text NULL,
  "simple_mode" boolean NOT NULL DEFAULT false,
  "alert_role_id" text NULL,
  PRIMARY KEY ("guild_id")
);
-- Create "thread_open_alerts" table
CREATE TABLE "thread_open_alerts" (
  "guild_id" text NOT NULL,
  "user_id" text NOT NULL,
  PRIMARY KEY ("guild_id", "user_id")
);
-- Create "threads" table
CREATE TABLE "threads" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guild_id" text NOT NULL,
  "mod_thread_id" text NOT NULL,
  "user_id" text NOT NULL,
  "created_by_id" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "closed_by_id" text NULL,
  "closed_at" timestamptz NULL,
  "last_local_thread_message_id" integer NOT NULL DEFAULT 0,
  "category_id" integer NULL,
  "user_thread_id" text NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "threads_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "threads_category_id_idx" to table: "threads"
CREATE INDEX "threads_category_id_idx" ON "threads" ("category_id");
-- Create index "threads_guild_id_idx" to table: "threads"
CREATE INDEX "threads_guild_id_idx" ON "threads" ("guild_id");
-- Create "scheduled_thread_closes" table
CREATE TABLE "scheduled_thread_closes" (
  "thread_id" integer NOT NULL,
  "scheduled_by_id" text NOT NULL,
  "silent" boolean NOT NULL DEFAULT false,
  "close_at" timestamptz NOT NULL,
  PRIMARY KEY ("thread_id"),
  CONSTRAINT "scheduled_thread_closes_thread_id_fkey" FOREIGN KEY ("thread_id") REFERENCES "threads" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "snippets" table
CREATE TABLE "snippets" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guild_id" text NOT NULL,
  "command_id" text NOT NULL,
  "created_by_id" text NOT NULL,
  "name" text NOT NULL,
  "content" text NOT NULL,
  "times_used" integer NOT NULL DEFAULT 0,
  "last_used_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "last_updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "snippets_guild_id_name_key" UNIQUE ("guild_id", "name")
);
-- Create "snippet_updates" table
CREATE TABLE "snippet_updates" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "snippet_id" integer NOT NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "updated_by" text NOT NULL,
  "old_content" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "snippet_updates_snippet_id_fkey" FOREIGN KEY ("snippet_id") REFERENCES "snippets" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "snippet_updates_snippet_id_idx" to table: "snippet_updates"
CREATE INDEX "snippet_updates_snippet_id_idx" ON "snippet_updates" ("snippet_id");
-- Create "thread_messages" table
CREATE TABLE "thread_messages" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "local_thread_message_id" integer NOT NULL,
  "guild_id" text NOT NULL,
  "thread_id" integer NOT NULL,
  "user_id" text NOT NULL,
  "user_message_id" text NOT NULL,
  "staff_id" text NULL,
  "guild_message_id" text NOT NULL,
  "anon" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id"),
  CONSTRAINT "thread_messages_thread_id_local_thread_message_id_key" UNIQUE ("thread_id", "local_thread_message_id"),
  CONSTRAINT "thread_messages_thread_id_fkey" FOREIGN KEY ("thread_id") REFERENCES "threads" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "thread_messages_thread_id_idx" to table: "thread_messages"
CREATE INDEX "thread_messages_thread_id_idx" ON "thread_messages" ("thread_id");
-- Create "thread_reply_alerts" table
CREATE TABLE "thread_reply_alerts" (
  "thread_id" integer NOT NULL,
  "user_id" text NOT NULL,
  PRIMARY KEY ("thread_id", "user_id"),
  CONSTRAINT "thread_reply_alerts_thread_id_fkey" FOREIGN KEY ("thread_id") REFERENCES "threads" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "ticket_panels" table
CREATE TABLE "ticket_panels" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guild_id" text NOT NULL,
  "channel_id" text NOT NULL,
  "message_id" text NOT NULL,
  "panel_json_data" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "ticket_panels_message_id_key" UNIQUE ("message_id")
);
-- Create index "ticket_panels_guild_id_idx" to table: "ticket_panels"
CREATE INDEX "ticket_panels_guild_id_idx" ON "ticket_panels" ("guild_id");
-- Create "ticket_panel_categories" table
CREATE TABLE "ticket_panel_categories" (
  "ticket_panel_id" integer NOT NULL,
  "category_id" integer NOT NULL,
  PRIMARY KEY ("ticket_panel_id", "category_id"),
  CONSTRAINT "ticket_panel_categories_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "ticket_panel_categories_ticket_panel_id_fkey" FOREIGN KEY ("ticket_panel_id") REFERENCES "ticket_panels" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "ticket_panel_categories_category_id_idx" to table: "ticket_panel_categories"
CREATE INDEX "ticket_panel_categories_category_id_idx" ON "ticket_panel_categories" ("category_id");
