-- Create enum type "social_level_up_notification_mode"
CREATE TYPE "social_level_up_notification_mode" AS ENUM ('NONE', 'DM', 'CHANNEL');
-- Create "social_channels" table
CREATE TABLE "social_channels" (
  "guild_id" text NOT NULL,
  "channel_id" text NOT NULL,
  "ignored" boolean NOT NULL DEFAULT false,
  "multiplier" integer NOT NULL DEFAULT 1,
  PRIMARY KEY ("guild_id", "channel_id"),
  CONSTRAINT "social_channels_multiplier_check" CHECK (multiplier >= 1)
);
-- Create "social_guild_settings" table
CREATE TABLE "social_guild_settings" (
  "guild_id" text NOT NULL,
  "required_messages" integer NULL,
  "required_messages_timespan" integer NULL,
  "xp_gain" integer NULL,
  "required_xp_base" integer NULL,
  "required_xp_multiplier" integer NULL,
  "level_up_notification_mode" "social_level_up_notification_mode" NOT NULL DEFAULT 'NONE',
  "level_up_notification_fallback_channel_id" text NULL,
  "level_up_notification_message" text NULL,
  PRIMARY KEY ("guild_id"),
  CONSTRAINT "social_guild_settings_required_xp_base_check" CHECK ((required_xp_base IS NULL) OR (required_xp_base >= 1)),
  CONSTRAINT "social_guild_settings_required_xp_multiplier_check" CHECK ((required_xp_multiplier IS NULL) OR (required_xp_multiplier >= 1))
);
-- Create "social_interactions" table
CREATE TABLE "social_interactions" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guild_id" text NOT NULL,
  "command_id" text NULL,
  "name" text NOT NULL,
  "content" text NOT NULL,
  "color" text NULL,
  "plain_content" text NULL,
  "attachment_url" text NULL,
  "uses" integer NOT NULL DEFAULT 0,
  "embed" boolean NOT NULL DEFAULT false,
  "allow_targets" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id"),
  CONSTRAINT "social_interactions_guild_id_name_key" UNIQUE ("guild_id", "name")
);
-- Create index "social_interactions_guild_id_command_id_idx" to table: "social_interactions"
CREATE INDEX "social_interactions_guild_id_command_id_idx" ON "social_interactions" ("guild_id", "command_id") WHERE (command_id IS NOT NULL);
-- Create "social_rewards" table
CREATE TABLE "social_rewards" (
  "guild_id" text NOT NULL,
  "role_id" text NOT NULL,
  "level" integer NOT NULL,
  "clean" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("guild_id", "role_id"),
  CONSTRAINT "social_rewards_level_check" CHECK (level >= 0)
);
-- Create "social_roles" table
CREATE TABLE "social_roles" (
  "guild_id" text NOT NULL,
  "role_id" text NOT NULL,
  "multiplier" integer NOT NULL DEFAULT 1,
  PRIMARY KEY ("guild_id", "role_id"),
  CONSTRAINT "social_roles_multiplier_check" CHECK (multiplier >= 1)
);
-- Create "social_users" table
CREATE TABLE "social_users" (
  "guild_id" text NOT NULL,
  "user_id" text NOT NULL,
  "xp" integer NOT NULL DEFAULT 0,
  "ignored" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("guild_id", "user_id")
);
