-- Create "automoderator_report_messages" table
CREATE TABLE "automoderator_report_messages" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "report_id" integer NOT NULL,
  "position" smallint NOT NULL,
  "message_id" text NOT NULL,
  "channel_id" text NOT NULL,
  "author_id" text NOT NULL,
  "author_tag" text NOT NULL,
  "content" text NULL,
  "image_url" text NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "automoderator_report_messages_report_id_message_id_key" UNIQUE ("report_id", "message_id"),
  CONSTRAINT "automoderator_report_messages_report_id_position_key" UNIQUE ("report_id", "position"),
  CONSTRAINT "automoderator_report_messages_report_id_fkey" FOREIGN KEY ("report_id") REFERENCES "automoderator_reports" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "automoderator_report_messages_position_check" CHECK ("position" >= 1)
);
