-- Create enum type "ama_question_state"
CREATE TYPE "ama_question_state" AS ENUM ('PENDING_MOD_REVIEW', 'PENDING_GUEST_REVIEW', 'FLAGGED', 'APPROVED', 'DENIED');
-- Create "ama_sessions" table
CREATE TABLE "ama_sessions" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guild_id" text NOT NULL,
  "mod_queue_id" text NULL,
  "flagged_queue_id" text NULL,
  "guest_queue_id" text NULL,
  "title" text NOT NULL,
  "answers_channel_id" text NOT NULL,
  "prompt_channel_id" text NOT NULL,
  "allowed_question_uploads" integer NOT NULL DEFAULT 2,
  "ended" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
-- Create "dashboard_grants" table
CREATE TABLE "dashboard_grants" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guild_id" text NOT NULL,
  "user_id" text NOT NULL,
  "created_by_id" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "dashboard_grants_guild_id_user_id_key" UNIQUE ("guild_id", "user_id")
);
-- Create "ama_prompt_data" table
CREATE TABLE "ama_prompt_data" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "ama_id" integer NOT NULL,
  "prompt_message_id" text NOT NULL,
  "prompt_json_data" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "ama_prompt_data_ama_id_key" UNIQUE ("ama_id"),
  CONSTRAINT "ama_prompt_data_prompt_message_id_key" UNIQUE ("prompt_message_id"),
  CONSTRAINT "ama_prompt_data_ama_id_fkey" FOREIGN KEY ("ama_id") REFERENCES "ama_sessions" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "ama_questions" table
CREATE TABLE "ama_questions" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "ama_id" integer NOT NULL,
  "author_id" text NOT NULL,
  "state" "ama_question_state" NOT NULL DEFAULT 'PENDING_MOD_REVIEW',
  "content" text NOT NULL,
  "mod_queue_message_id" text NULL,
  "guest_queue_message_id" text NULL,
  "flagged_queue_message_id" text NULL,
  "answers_message_id" text NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "ama_questions_ama_id_fkey" FOREIGN KEY ("ama_id") REFERENCES "ama_sessions" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "ama_questions_ama_id_idx" to table: "ama_questions"
CREATE INDEX "ama_questions_ama_id_idx" ON "ama_questions" ("ama_id");
-- Create "experiments" table
CREATE TABLE "experiments" (
  "name" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NULL,
  "range_start" integer NOT NULL,
  "range_end" integer NOT NULL,
  PRIMARY KEY ("name")
);
-- Create "experiment_overrides" table
CREATE TABLE "experiment_overrides" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guild_id" text NOT NULL,
  "experiment_name" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "experiment_overrides_guild_id_experiment_name_key" UNIQUE ("guild_id", "experiment_name"),
  CONSTRAINT "experiment_overrides_experiment_name_fkey" FOREIGN KEY ("experiment_name") REFERENCES "experiments" ("name") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create index "experiment_overrides_experiment_name_idx" to table: "experiment_overrides"
CREATE INDEX "experiment_overrides_experiment_name_idx" ON "experiment_overrides" ("experiment_name");
