-- Declarative schema (source of truth for `atlas migrate diff`).
--
-- Naming convention: snake_case tables/columns, mapped to camelCase JS via the
-- `postgres.camel` transform passed to `createDb()` (SimplyChords' convention —
-- see docs/roadmap/02-foundation.md Part A step 2 for the decision writeup).
--
-- Reproduces the 6 current Prisma models 1:1 (see prisma/schema.prisma and
-- docs/roadmap/01-architecture.md §5): Experiment, ExperimentOverride,
-- DashboardGrant, AMASession, AMAPromptData, AMAQuestion (+ AMAQuestionState).
--
-- Note: Prisma's `@updatedAt` on AMAQuestion.updatedAt was a Prisma-client-side
-- behavior (set on every client `.update()` call), not a DB trigger. There is no
-- trigger reproducing it here — the route migration (raw SQL, see #128) is
-- responsible for setting `updated_at = now()` explicitly on updates.

CREATE TABLE experiments (
  name        TEXT PRIMARY KEY,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ,
  range_start INTEGER NOT NULL,
  range_end   INTEGER NOT NULL
);

CREATE TABLE experiment_overrides (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id        TEXT NOT NULL,
  experiment_name TEXT NOT NULL REFERENCES experiments (name) ON DELETE CASCADE,

  CONSTRAINT experiment_overrides_guild_id_experiment_name_key UNIQUE (guild_id, experiment_name)
);

CREATE INDEX experiment_overrides_experiment_name_idx ON experiment_overrides (experiment_name);

CREATE TABLE dashboard_grants (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id       TEXT NOT NULL,
  user_id        TEXT NOT NULL,
  created_by_id  TEXT NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT dashboard_grants_guild_id_user_id_key UNIQUE (guild_id, user_id)
);

CREATE TABLE ama_sessions (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id                 TEXT NOT NULL,
  queue_id                 TEXT,
  title                    TEXT NOT NULL,
  -- Nullable since #316: NULL means this AMA publishes nowhere on Discord, and the public answers page
  -- (`share_token` below) is the only surface an answer ever reaches. Every path that would otherwise
  -- post/edit/delete an answers-channel message skips the Discord call and leaves
  -- `ama_questions.answers_message_id` null; the question still transitions to 'ASKED' with an
  -- `asked_at`, which is what the public page reads. Switching an existing AMA either way only affects
  -- questions sent afterwards -- already-posted messages are left alone rather than retro-deleted.
  answers_channel_id       TEXT,
  prompt_channel_id        TEXT NOT NULL,
  -- Max files on the submit modal. Must be 0 when the AMA has no Discord message surface at all
  -- (answers_channel_id IS NULL AND queue_id IS NULL) -- attachments are never persisted here, every
  -- consumer reads them back off whichever live Discord message currently shows the question (see
  -- services/api's questions/util.ts `resolveQuestionAttachments`), so with no message they'd be
  -- silently dropped. Enforced in services/api (createAMA/updateAMA) rather than by a CHECK, so the
  -- dashboard can surface *why* the field is disabled instead of failing on a constraint violation.
  allowed_question_uploads INTEGER NOT NULL DEFAULT 2,
  ended                    BOOLEAN NOT NULL DEFAULT false,
  -- Optional automated close date (#290), settable at creation and editable retroactively (while the AMA is
  -- still active -- updateAMA.ts already rejects any edit once `ended`) via services/ama-bot's
  -- scheduledCloseSweep.ts, which flips `ended` the same way `/ama end` does once this lapses.
  scheduled_close_at       TIMESTAMPTZ,
  -- Decouples approving a question from posting it (#293 follow-up, "Tommy" AMA question management).
  -- Off (default): unchanged behavior, approval == posting. On: approval only sets state to APPROVED,
  -- an answer can be prepared ahead of time (the dashboard's answer editor), and posting to
  -- answers_channel_id only happens via the dashboard's explicit Send action.
  prepared_answers_enabled BOOLEAN NOT NULL DEFAULT false,
  -- Splits "does review exist" from "does it have a Discord channel" -- lets review be enabled but
  -- dashboard-only (no queue message posted anywhere). Review now has one unified pool of reviewers
  -- (mods in Discord and/or dashboard, plus any configured `guest_ids` via the dashboard), so a
  -- dash-only review stage always has somewhere to be handled. Backfilled for existing rows as
  -- `(mod_queue_id IS NOT NULL)`, which exactly preserves prior behavior: a stage that was never
  -- configured stays fully skipped, not silently reinterpreted.
  -- Submission (prompt_channel_id) stays deliberately excluded from this pattern -- it's the only entry
  -- point a question can arrive through (the prompt message's "Submit a question" button), so there'd be
  -- nothing left to submit *with*. Publishing used to be excluded for the same "cannot be dash-only"
  -- reason but no longer is; see answers_channel_id above (#316).
  review_enabled           BOOLEAN NOT NULL DEFAULT false,
  -- Opaque id backing the public, unauthenticated read-only answers page (`/ama-answers/:shareToken`).
  -- Generated unconditionally at creation (see createAMA.ts) -- pre-existing rows were backfilled a
  -- generated value in the same migration that added this column.
  share_token              TEXT NOT NULL UNIQUE,
  -- Known guest user ids for this AMA (freeform, editable retroactively). Guests get scoped dashboard
  -- access to this AMA's Questions/Analytics pages regardless of their general dashboard/guild-manage
  -- status (see services/api's `'or-ama-guest'` auth path) and can act on the queue exactly like a mod
  -- (approve/deny/merge/prepare+send answers/tag) -- plus back the "answered by" picker in the
  -- dashboard's answer editor. Empty by default, in which case the picker falls back to its original
  -- free-text/default-to-self behavior and there are no non-manager dashboard users for this AMA.
  guest_ids                TEXT[] NOT NULL DEFAULT '{}',
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT ama_sessions_review_enabled_check CHECK (review_enabled OR queue_id IS NULL)
);

CREATE TABLE ama_prompt_data (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ama_id            INTEGER NOT NULL UNIQUE REFERENCES ama_sessions (id) ON DELETE CASCADE,
  prompt_message_id TEXT NOT NULL UNIQUE,
  prompt_json_data  TEXT NOT NULL
);

-- 'ASKED' (#293 follow-up) is the only state meaning "posted to the answers channel" -- 'APPROVED'
-- universally means "approved, not necessarily posted yet" now. When `prepared_answers_enabled` is
-- off, the approve paths set 'ASKED' directly (posting immediately, same as the old 'APPROVED'
-- behavior); when on, they hold at 'APPROVED' and only the dashboard's Send action produces 'ASKED'.
-- Mod review and guest review used to be two sequential stages ('PENDING_MOD_REVIEW' then
-- 'PENDING_GUEST_REVIEW'), with a separate read-only 'FLAGGED' dead-end reachable only from mod review.
-- Both are gone: guests now review the same single queue via dashboard access instead of a dedicated
-- Discord channel, and flagging (a dead-end with no forward path) was removed outright.
CREATE TYPE ama_question_state AS ENUM (
  'PENDING_REVIEW',
  'APPROVED',
  'DENIED',
  'ASKED'
);

CREATE TABLE ama_questions (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ama_id                   INTEGER NOT NULL REFERENCES ama_sessions (id) ON DELETE CASCADE,
  author_id                TEXT NOT NULL,
  state                    ama_question_state NOT NULL DEFAULT 'PENDING_REVIEW',
  content                  TEXT NOT NULL,
  queue_message_id         TEXT,
  answers_message_id       TEXT,
  -- Answer fields (#293 follow-up), written from the dashboard only -- the bot-side "Add Answer" modal
  -- this comment used to also name was never actually built (#200, still open). Populated ahead of Send
  -- when `ama_sessions.prepared_answers_enabled` is on, and since #327 also editable afterwards, on an
  -- already-'ASKED' question (which re-renders the live answers-channel message rather than reposting).
  -- All nullable: a question can reach 'APPROVED' with no answer prepared yet, and an AMA answered live
  -- on stream may never record one at all.
  answer_content           TEXT,
  answer_image_url         TEXT,
  answered_by_id           TEXT,
  answered_at              TIMESTAMPTZ,
  -- Set once, on the transition to 'ASKED' (every path that posts to the answers channel writes it).
  -- The public answers page used to read `updated_at` for this, which stopped being correct once #327
  -- made an already-sent answer editable -- fixing a typo months later would have moved the question's
  -- displayed "asked at" to today. Nullable: non-'ASKED' rows never have one, and rows predating this
  -- column were backfilled from `updated_at` (the best approximation available).
  asked_at                 TIMESTAMPTZ,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Referenced by ama_question_tag_assignments' composite FK below, so a tag assignment's own ama_id
  -- is guaranteed to match the question it's attached to, not just the tag.
  CONSTRAINT ama_questions_id_ama_id_key UNIQUE (id, ama_id)
);

CREATE INDEX ama_questions_ama_id_idx ON ama_questions (ama_id);

-- Duplicate-merge target (#293 follow-up): merging question A into B deletes A and adds an
-- `ama_question_askers` row for B recording A's author. B's own `author_id` *can* land in here when
-- someone asks twice and both of their questions get merged together, so anything counting "other
-- people who asked this" has to filter it back out (see `countExtraAskers`). The live Discord embed
-- shows a bare count of those askers (#326) and never their names -- who they are stays a
-- dashboard-only detail; `content` preserves A's original
-- question text for the dashboard's merged-duplicate display, snapshotted at merge time since the
-- row it came from is deleted. Nullable, and deliberately never backfilled for rows merged before
-- this column existed -- that content was already destroyed by the delete, unrecoverably.
CREATE TABLE ama_question_askers (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id INTEGER NOT NULL REFERENCES ama_questions (id) ON DELETE CASCADE,
  author_id   TEXT NOT NULL,
  content     TEXT,
  merged_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT ama_question_askers_question_id_author_id_key UNIQUE (question_id, author_id)
);

CREATE INDEX ama_question_askers_question_id_idx ON ama_question_askers (question_id);

-- Per-AMA-session freeform mod-side tags (#293 follow-up) -- dashboard-only, not reusable across
-- sessions (genuinely temporary, scoped to a single AMA's lifetime).
CREATE TABLE ama_question_tags (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ama_id     INTEGER NOT NULL REFERENCES ama_sessions (id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT ama_question_tags_ama_id_name_key UNIQUE (ama_id, name),
  -- Referenced by ama_question_tag_assignments' composite FK below, so a tag assignment's own ama_id
  -- is guaranteed to match the tag it's attached to, not just the question.
  CONSTRAINT ama_question_tags_id_ama_id_key UNIQUE (id, ama_id)
);

CREATE INDEX ama_question_tags_ama_id_idx ON ama_question_tags (ama_id);

-- ama_id is redundant with both question_id -> ama_questions.ama_id and tag_id ->
-- ama_question_tags.ama_id individually, but carrying it here lets both composite FKs below pin it to
-- the *same* value on both sides -- which is what actually rules out a tag from AMA A ever getting
-- assigned to a question in AMA B. Set by the application at insert time (see updateQuestion.ts),
-- always equal to the (already-validated-matching) ama_id of both the question and the tag.
CREATE TABLE ama_question_tag_assignments (
  question_id INTEGER NOT NULL,
  tag_id      INTEGER NOT NULL,
  ama_id      INTEGER NOT NULL,

  PRIMARY KEY (question_id, tag_id),
  CONSTRAINT ama_question_tag_assignments_question_fkey FOREIGN KEY (question_id, ama_id)
    REFERENCES ama_questions (id, ama_id) ON DELETE CASCADE,
  CONSTRAINT ama_question_tag_assignments_tag_fkey FOREIGN KEY (tag_id, ama_id)
    REFERENCES ama_question_tags (id, ama_id) ON DELETE CASCADE
);

CREATE INDEX ama_question_tag_assignments_tag_id_idx ON ama_question_tag_assignments (tag_id);
CREATE INDEX ama_question_tag_assignments_ama_id_idx ON ama_question_tag_assignments (ama_id);

-- ModMail (M5, ticket-system rebuild — see docs/roadmap/06-modmail-port.md and issue #152).
--
-- Reproduces the 9 carried-forward models from `ChatSift/ModMail`'s `prisma/schema.prisma`
-- (GuildSettings, Snippet, SnippetUpdates, Thread, ThreadMessage, ScheduledThreadClose, Block,
-- ThreadOpenAlert, ThreadReplyAlert), mostly 1:1, plus two new models (Category, TicketPanel)
-- and a join table (TicketPanelCategory) for the new create-flow.
--
-- Design decisions confirmed 2026-07-23 (owner sign-off, see issue #152 discussion) that shape
-- this section:
--   - Category routing is forum-tag-only: every guild has a single mod forum
--     (guild_settings.mod_forum_id); categories map to a tag within it (categories.forum_tag_id),
--     not a separate forum channel per category.
--   - No staff-role concept was added. The mention/user-ID auto-embed QOL feature (bot-side, not
--     a schema concern) only fires on relayed *user* messages, never staff replies — decided by
--     checking thread_messages.staff_id/user_id on the message being relayed, not by a role.
--   - Multiple ticket panels per guild are expected, each scoped to a subset of a guild's
--     categories chosen at panel-creation time — hence ticket_panel_categories.
--
-- threads.channel_id (old Prisma model) is renamed to mod_thread_id here, disambiguating it from
-- the new user_channel_id now that a thread has two Discord-channel concepts (mod-forum side vs.
-- the user's side, panel private thread or DM channel). Free to do since this table has no prior
-- rows in the new schema.

-- Registry of branded, single-guild ModMail deployments (#216). A row here is what makes a guild
-- "owned" by a custom instance: the public modmail-bot deployment no-ops for any guild listed here,
-- and services/api routes every Discord call for that guild through this instance's token instead of
-- MODMAIL_BOT_TOKEN. Rows are inserted by hand (see docs/workflow.md) alongside adding the matching
-- docker-compose service -- there is deliberately no API/dashboard CRUD for this table, since it
-- holds a live bot token. See docs/roadmap/01-architecture.md §8 for the full design.
CREATE TABLE modmail_instances (
  -- Slug, matched against the deployment's own MODMAIL_INSTANCE_ID env var. Stable; renaming one
  -- means redeploying the service that carries it.
  id         TEXT PRIMARY KEY,
  -- One instance per guild, enforced here rather than in application code -- the whole ownership
  -- model in docs/roadmap/01-architecture.md §8 rests on this being unambiguous.
  guild_id   TEXT NOT NULL UNIQUE,
  -- The custom bot application's token, encrypted at rest with ENCRYPTION_KEY (AES-256-GCM), same
  -- key the JWT signing path already uses. Encrypted rather than plain because a Postgres dump or a
  -- backup snapshot would otherwise carry live bot credentials for every partner.
  token      TEXT NOT NULL,
  -- Display name shown in place of "ModMail" throughout this guild's dashboard.
  label      TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE guild_settings (
  guild_id                 TEXT PRIMARY KEY,
  mod_forum_id             TEXT,
  default_greeting_message TEXT,
  farewell_message         TEXT,
  simple_mode              BOOLEAN NOT NULL DEFAULT false,
  alert_role_id            TEXT,
  -- Author label shown on anonymous staff replies (services/modmail-bot's lib/relay.ts), supports a
  -- `{{ guildName }}` placeholder. NULL falls back to the "{{ guildName }} Team" default at render time
  -- rather than being baked in here, so the default can change later without a data migration.
  anon_reply_label         TEXT,
  -- How many tickets a single user may have open at once in this guild, summed across all categories.
  -- Enforced by services/modmail-bot at ticket-creation time (lib/threads.ts's
  -- countActiveTicketsForUser), not a DB constraint, since it's a soft business rule checked
  -- alongside a Discord API call, not something the write itself can violate.
  max_concurrent_threads   INTEGER NOT NULL DEFAULT 1,
  -- How long, after a ticket closes, before the user's private thread is actually deleted ("nuked") --
  -- see `scheduled_thread_nukes` below. The thread is locked (but deliberately left unarchived, see
  -- services/modmail-bot's `lib/threadClose.ts`) immediately on close regardless. NULL (the default)
  -- means "never nuke" -- an explicit opt-in is required to schedule deletion at all; when opted out,
  -- the thread just sits locked until Discord's own inactivity auto-archive eventually catches it.
  nuke_delay_minutes       INTEGER,
  -- Whether the greeting (category's, falling back to default_greeting_message) is posted before the
  -- user's own opener message is relayed to staff, instead of after. Defaults to false (after) --
  -- matching prod ChatSift/ModMail's existing behavior of relay-then-greet.
  greeting_before_opener   BOOLEAN NOT NULL DEFAULT false,
  -- Consent toggle for recording full message content into `thread_message_content` (see below) --
  -- defaults to false since capturing every reply and surrounding message in a ticket is a real privacy
  -- decision, not a default a guild should be opted into silently. `enabled_by`/`enabled_at` form an
  -- audit trail of who opted in and when; services/api's updateConfig.ts only sets them on the
  -- false->true transition and deliberately leaves them populated after a later disable (see #261).
  record_thread_content                  BOOLEAN NOT NULL DEFAULT false,
  record_thread_content_enabled_by       TEXT,
  record_thread_content_enabled_at       TIMESTAMPTZ,
  -- Whether this guild's ModMail runs on the pre-M5 DM front door instead of ticket panels (#216).
  -- Only meaningful for a guild with a modmail_instances row -- the public deployment never reads it,
  -- and services/api rejects setting it true for a guild with no custom instance. When on, ticket
  -- panels go inert (see the create-ticket component) and the panel-specific settings below stop
  -- applying, but nothing about them is deleted: flipping this back off restores the panel flow as-is.
  dm_mode                                BOOLEAN NOT NULL DEFAULT false,

  CONSTRAINT guild_settings_max_concurrent_threads_check CHECK (max_concurrent_threads >= 1),
  CONSTRAINT guild_settings_nuke_delay_minutes_check CHECK (nuke_delay_minutes IS NULL OR nuke_delay_minutes >= 1)
);

CREATE TABLE categories (
  id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id               TEXT NOT NULL,
  name                   TEXT NOT NULL,
  emoji                  TEXT,
  description            TEXT,
  greeting_message       TEXT,
  forum_tag_id           TEXT,
  sort_order             INTEGER NOT NULL DEFAULT 0,
  -- Per-category override of guild_settings.max_concurrent_threads, for guilds that want to cap a
  -- specific category (e.g. "Bug Reports") tighter than their general limit. NULL means "inherit the
  -- guild's general limit" -- this is the "default" the feature spec means, not a value copied in at
  -- category-creation time, so it keeps tracking the guild setting if that changes later. Must be
  -- <= guild_settings.max_concurrent_threads; enforced at write time by services/api (createCategory/
  -- updateCategory) and defensively re-clamped at read time by services/modmail-bot
  -- (categorySelect.ts) in case the guild setting was lowered after this was set.
  max_concurrent_threads INTEGER,

  CONSTRAINT categories_guild_id_name_key UNIQUE (guild_id, name),
  CONSTRAINT categories_max_concurrent_threads_check CHECK (max_concurrent_threads IS NULL OR max_concurrent_threads >= 1)
);

CREATE INDEX categories_guild_id_idx ON categories (guild_id);

-- Tag-based routing (see comment above) is ambiguous if two categories in the same guild share a
-- forum tag; partial (forum_tag_id nullable, since a category can be unconfigured) unique index
-- enforces one category per tag per guild.
CREATE UNIQUE INDEX categories_guild_id_forum_tag_id_key ON categories (guild_id, forum_tag_id) WHERE forum_tag_id IS NOT NULL;

CREATE TABLE ticket_panels (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id        TEXT NOT NULL,
  channel_id      TEXT NOT NULL,
  message_id      TEXT NOT NULL UNIQUE,
  panel_json_data TEXT NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ticket_panels_guild_id_idx ON ticket_panels (guild_id);

CREATE TABLE ticket_panel_categories (
  ticket_panel_id INTEGER NOT NULL REFERENCES ticket_panels (id) ON DELETE CASCADE,
  category_id     INTEGER NOT NULL REFERENCES categories (id) ON DELETE CASCADE,

  PRIMARY KEY (ticket_panel_id, category_id)
);

CREATE INDEX ticket_panel_categories_category_id_idx ON ticket_panel_categories (category_id);

CREATE TABLE threads (
  id                            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id                      TEXT NOT NULL,
  mod_thread_id                 TEXT NOT NULL,
  user_id                       TEXT NOT NULL,
  created_by_id                 TEXT NOT NULL,
  created_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
  closed_by_id                  TEXT,
  closed_at                     TIMESTAMPTZ,
  last_local_thread_message_id  INTEGER NOT NULL DEFAULT 0,
  category_id                   INTEGER REFERENCES categories (id) ON DELETE SET NULL,
  -- The Discord channel the bot relays a user's side of the conversation through -- a private thread
  -- for the M5 panel flow ('panel' origin below), or the opener's DM channel for DM mode (#216, P4).
  -- Named generically (not "...thread_id") because it isn't always a thread; a DM channel id is stable
  -- per (user, bot application) pair, which is what lets the relay/edit/delete-sync/`/reply` code work
  -- unchanged for both origins -- see docs/roadmap/01-architecture.md §8.
  user_channel_id                TEXT,
  -- How this ticket was opened. 'panel' is the M5 flow (user_channel_id is a real private thread this
  -- bot created and may lock/delete); 'dm' means user_channel_id is the opener's DM channel id, which
  -- must never be locked, archived or deleted. Only 'dm' is possible for a guild running DM mode
  -- (guild_settings.dm_mode); every other ticket is 'panel'.
  origin                        TEXT NOT NULL DEFAULT 'panel',
  -- Which legacy migration run produced this row; NULL for a natively created ticket. Written by
  -- packages/private/db/src/scripts/migrateLegacyModmail.ts's --source flag. Replaces the inferential
  -- "origin = 'dm' AND user_channel_id IS NULL" predicate that script used to identify its own rows,
  -- which could neither tell two legacy sources apart (so migrating one blocked every later run) nor
  -- distinguish a migrated row from a natively created DM-mode ticket with a missing channel id.
  migration_source              TEXT,

  CONSTRAINT threads_origin_check CHECK (origin IN ('panel', 'dm'))
);

CREATE INDEX threads_guild_id_idx ON threads (guild_id);
CREATE INDEX threads_category_id_idx ON threads (category_id);
-- Both looked up on every relayed message/reply command in services/modmail-bot: user_channel_id to
-- find the ticket a private-thread/DM message belongs to, mod_thread_id to find the ticket a /reply or
-- /reply-q command was run in.
CREATE INDEX threads_user_channel_id_idx ON threads (user_channel_id) WHERE user_channel_id IS NOT NULL;
CREATE INDEX threads_mod_thread_id_idx ON threads (mod_thread_id);
-- Back the two concurrent-thread-limit counts in `lib/threads.ts`, both partial on
-- `closed_at IS NULL` since a closed ticket never counts toward either limit and closed rows vastly
-- outnumber open ones over a guild's lifetime. `countActiveTicketsForUser` (the general, guild-wide
-- limit, checked on every ticket-panel click) filters on guild + user only, matching the first index
-- below; `countOpenThreadsForUserInCategory` (the per-category limit, checked on every category pick)
-- additionally filters on `category_id`, matching the second, wider index instead.
CREATE INDEX threads_guild_id_user_id_open_idx ON threads (guild_id, user_id) WHERE closed_at IS NULL;
CREATE INDEX threads_guild_id_user_id_category_id_open_idx ON threads (guild_id, user_id, category_id) WHERE closed_at IS NULL;
-- Only ever read by migrateLegacyModmail.ts (its re-run guard and every target-side --verify count),
-- and partial because natively created rows -- the overwhelming majority -- leave it NULL.
CREATE INDEX threads_migration_source_idx ON threads (migration_source) WHERE migration_source IS NOT NULL;

-- Tracks a ticket from the moment its private thread is created (services/modmail-bot's
-- createTicket.ts for a no-category panel, categorySelect.ts once a category's been picked) until
-- finishTicketCreation actually inserts a `threads` row for it. The Redis-side PendingTicketStore (same
-- TTL) tracks this same window for routing incoming events, but a Redis key TTL alone gives nothing to
-- act on when it lapses -- this table is the durable side a periodic sweep polls to delete private
-- threads whose setup was abandoned (e.g. the user never sent an opening message), and also what
-- `countActiveTicketsForUser`/`countOpenThreadsForUserInCategory` count as "already holding a slot" for
-- tickets still mid-setup. `category_id` is NULL for a no-category panel's pending ticket, same meaning
-- as `threads.category_id`.
CREATE TABLE pending_tickets (
  private_thread_id TEXT PRIMARY KEY,
  guild_id          TEXT NOT NULL,
  user_id           TEXT NOT NULL,
  category_id       INTEGER REFERENCES categories (id) ON DELETE SET NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Backs `countActiveTicketsForUser`'s pending-ticket half of the count (see above).
CREATE INDEX pending_tickets_guild_id_user_id_idx ON pending_tickets (guild_id, user_id);
-- Backs `countOpenThreadsForUserInCategory`'s pending-ticket half of the count -- without this, a
-- category pick made while an earlier pick for the *same* category is still pending (private thread
-- created, opening message not sent yet, so no `threads` row exists for it either) wouldn't be counted
-- against that category's limit, letting a burst of picks blow past it the same way
-- `countActiveTicketsForUser`'s own pending half prevents for the general limit.
CREATE INDEX pending_tickets_guild_id_user_id_category_id_idx ON pending_tickets (guild_id, user_id, category_id);

CREATE TABLE thread_messages (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_thread_message_id  INTEGER NOT NULL,
  guild_id                 TEXT NOT NULL,
  thread_id                INTEGER NOT NULL REFERENCES threads (id) ON DELETE CASCADE,
  user_id                  TEXT NOT NULL,
  -- NULL for an `is_internal` row -- internal chatter never crosses into the user's private thread, so
  -- there's no corresponding message on that side to point at (unlike a user message or a `/reply`'s
  -- relayed copy, both of which always have one).
  user_message_id          TEXT,
  staff_id                 TEXT,
  guild_message_id         TEXT NOT NULL,
  anon                     BOOLEAN NOT NULL DEFAULT false,
  -- True for a plain message posted directly in the mod-forum thread (mod-to-mod discussion), as opposed
  -- to a user message relayed in or a `/reply`/`/reply-q` log copy -- never part of the user-facing
  -- exchange, so the dashboard renders it visually set apart from the actual conversation (#261).
  is_internal              BOOLEAN NOT NULL DEFAULT false,
  -- True for an automated message the bot itself posted (the opening greeting, `lib/ticketCreation.ts`'s
  -- `sendGreeting`; the closing farewell, `lib/threadClose.ts`'s `postFarewellMessage`) -- neither has a
  -- real "sender" the way every other row does (a user's own message, or a staff member's reply/internal
  -- note), so the dashboard needs to tell these apart from both to avoid misattributing them to whichever
  -- of `user_id`/`staff_id` this row happens to carry. `staff_id` is still populated when a farewell is
  -- attributed (non-anon) to the closing staffer -- `NULL` here covers both the greeting (never has an
  -- actor) and an anonymized farewell. Only ever inserted when recording is enabled, same as `is_internal`
  -- (see `insertThreadMessage`'s own doc comment) -- an unrecorded system row would carry zero information.
  is_system                BOOLEAN NOT NULL DEFAULT false,
  -- Set by `lib/userMessageLifecycle.ts`'s `MessageDelete` handler when the user deletes their own
  -- message client-side -- display-only (Phase 3, #261): the row and its `thread_message_content` are
  -- never touched by a user-side delete (see that table's own doc comment), this just lets the dashboard
  -- show a "deleted" badge alongside content that's still fully readable. Never set for a `/reply`-relayed
  -- or `is_internal` row -- those have their own, asymmetric true-delete handling instead.
  deleted_at               TIMESTAMPTZ,

  CONSTRAINT thread_messages_thread_id_local_thread_message_id_key UNIQUE (thread_id, local_thread_message_id)
);

CREATE INDEX thread_messages_thread_id_idx ON thread_messages (thread_id);

-- Sidecar to `thread_messages`, 1:1, same PK-is-FK shape as `scheduled_thread_closes`/
-- `scheduled_thread_nukes` below -- keeps the load-bearing `thread_messages` table lean while giving
-- recorded content its own lifecycle. Only written by services/modmail-bot's `insertThreadMessage` when
-- `guild_settings.record_thread_content` is on for the guild at relay time (see #261); a message with no
-- row here means it predates recording being enabled (or recording was never turned on), which the
-- dashboard thread view renders as a "not recorded" placeholder rather than backfilling or guessing.
CREATE TABLE thread_message_content (
  thread_message_id            INTEGER PRIMARY KEY REFERENCES thread_messages (id) ON DELETE CASCADE,
  content                      TEXT NOT NULL DEFAULT '',
  replied_to_thread_message_id INTEGER REFERENCES thread_messages (id) ON DELETE SET NULL,
  is_forwarded                 BOOLEAN NOT NULL DEFAULT false,
  attachments                  JSONB NOT NULL DEFAULT '[]', -- [{ url, filename, contentType, size }]
  stickers                     JSONB NOT NULL DEFAULT '[]', -- [{ id, name, formatType }]
  recorded_at                  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX thread_message_content_replied_to_idx ON thread_message_content (replied_to_thread_message_id)
  WHERE replied_to_thread_message_id IS NOT NULL;

-- One row per prior version of a `thread_message_content.content`, oldest edits first by `id` -- same
-- "archive the old value before overwriting" shape as `snippet_updates` below, written by
-- `lib/threads.ts`'s `updateRecordedMessageContent` (Phase 3, #261) instead of the blind overwrite it used
-- to do. No `edited_by` column -- unlike a snippet edit (staff-driven), a recorded message's editor is
-- always that message's own author, already known via `thread_messages.user_id`/`staff_id`.
CREATE TABLE thread_message_content_edits (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_message_id  INTEGER NOT NULL REFERENCES thread_message_content (thread_message_id) ON DELETE CASCADE,
  edited_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  old_content        TEXT NOT NULL
);

CREATE INDEX thread_message_content_edits_thread_message_id_idx ON thread_message_content_edits (thread_message_id);

CREATE TABLE scheduled_thread_closes (
  thread_id       INTEGER PRIMARY KEY REFERENCES threads (id) ON DELETE CASCADE,
  scheduled_by_id TEXT NOT NULL,
  silent          BOOLEAN NOT NULL DEFAULT false,
  -- Whether the farewell message this schedule eventually posts should be anonymous ("{guildName}
  -- Team") instead of attributed to scheduled_by_id -- mirrors /close now's anon option (and
  -- /reply's), see services/modmail-bot's lib/threadClose.ts. Attributed is the default, matching
  -- staff replies.
  anon            BOOLEAN NOT NULL DEFAULT false,
  close_at        TIMESTAMPTZ NOT NULL
);

-- A closed ticket's private thread is locked immediately (services/modmail-bot's `lib/threadClose.ts`)
-- but not deleted outright -- a row here is what a periodic sweep (`lib/threadNukeSweep.ts`) polls to
-- actually delete it once `guild_settings.nuke_delay_minutes` has passed. Only written when that column
-- is non-NULL (deletion is opt-in); a guild that never opts in simply never gets a row. Cascades with
-- `threads` since there's nothing left to nuke if the ticket row itself is gone.
CREATE TABLE scheduled_thread_nukes (
  thread_id INTEGER PRIMARY KEY REFERENCES threads (id) ON DELETE CASCADE,
  nuke_at   TIMESTAMPTZ NOT NULL
);

CREATE TABLE blocks (
  user_id    TEXT NOT NULL,
  guild_id   TEXT NOT NULL,
  expires_at TIMESTAMPTZ,

  PRIMARY KEY (user_id, guild_id)
);

CREATE TABLE thread_open_alerts (
  guild_id TEXT NOT NULL,
  user_id  TEXT NOT NULL,

  PRIMARY KEY (guild_id, user_id)
);

CREATE TABLE thread_reply_alerts (
  thread_id INTEGER NOT NULL REFERENCES threads (id) ON DELETE CASCADE,
  user_id   TEXT NOT NULL,

  PRIMARY KEY (thread_id, user_id)
);

-- Note: Prisma's `@updatedAt` on Snippet.lastUpdatedAt was client-side (set on every `.update()`
-- call), not a DB trigger — same caveat as AMAQuestion.updatedAt above. Whatever route/service
-- code updates a snippet's content is responsible for setting `last_updated_at = now()` itself.
CREATE TABLE snippets (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id            TEXT NOT NULL,
  command_id          TEXT NOT NULL,
  created_by_id       TEXT NOT NULL,
  name                TEXT NOT NULL,
  content             TEXT NOT NULL,
  attachment_url      TEXT,
  attachment_filename TEXT,
  times_used          INTEGER NOT NULL DEFAULT 0,
  last_used_at        TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT snippets_guild_id_name_key UNIQUE (guild_id, name),
  -- Backstop for the API's own validation (services/api's updateSnippet.ts clears attachment_filename
  -- whenever attachment_url is cleared) -- a filename with no URL to attach it to is meaningless.
  CONSTRAINT snippets_attachment_filename_requires_url_check CHECK (attachment_filename IS NULL OR attachment_url IS NOT NULL)
);

-- One row per edit, holding the *complete* prior state of every editable snippet field (#324) rather
-- than only the fields that changed -- which field(s) a given revision actually changed is derived at
-- read time by diffing consecutive snapshots (services/api's getSnippetUpdates.ts), so there's no
-- denormalized "changed fields" column that could ever disagree with the snapshots it describes.
-- Storing only the changed fields would also be ambiguous on the two nullable attachment columns,
-- where NULL would mean both "was unset" and "untouched by this edit".
CREATE TABLE snippet_updates (
  id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snippet_id              INTEGER NOT NULL REFERENCES snippets (id) ON DELETE CASCADE,
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by              TEXT NOT NULL,
  old_content             TEXT NOT NULL,
  -- NULL specifically means "row predates #324, the name was never captured" -- not "had no name",
  -- which is impossible since snippets.name is NOT NULL. Rows written before the snapshot widening
  -- (including everything the legacy Prisma migration backfilled) only ever recorded content edits,
  -- so the dashboard renders these content-only rather than inventing a name/attachment diff for them.
  old_name                TEXT,
  old_attachment_url      TEXT,
  old_attachment_filename TEXT
);

CREATE INDEX snippet_updates_snippet_id_idx ON snippet_updates (snippet_id);

-- Social (#343, leveling + social interactions — see docs/roadmap/10-social-port.md).
--
-- Reproduces the 6 models from `ChatSift/Social`'s `prisma/schema.prisma` (GuildSettings, Reward, User,
-- Channel, Role, SocialInteraction). Every table is `social_`-prefixed, following AMA's `ama_*`
-- (ModMail's unprefixed `guild_settings`/`threads` are grandfathered, not a pattern — and
-- `guild_settings` is literally taken).
--
-- The four deviations from legacy, collected here because the P5 migration script
-- (`migrateLegacySocial.ts`) has to account for every one of them; each is also documented at the
-- column it affects:
--   1. `level_up_notification_mode` values are uppercased to match this schema's other enum
--      (`ama_question_state`): None -> NONE, DM -> DM, Channel -> CHANNEL.
--   2. `social_channels.multiplier`/`social_roles.multiplier` are NOT NULL DEFAULT 1. Legacy's
--      `Int? @default(1)` was nullable, but a NULL there meant exactly 1 (every read site did
--      `multiplier ?? 1`), so the migration coalesces NULL -> 1 and nothing changes semantically.
--   3. `social_interactions` gets a surrogate `id` and a nullable `command_id` (see that table).
--   4. Composite primary keys are guild-first, where legacy's were (thing, guild) — see
--      `social_users`.
--
-- Bounds: legacy enforced its config bounds (required-messages 1-15, timespan 1-60s, xp-gain >= 1,
-- required-xp-base 1-500, required-xp-multiplier 1-100, channel multiplier 1-10) only in slash-command
-- option definitions, so they were never true of the data — only of writes made through the current
-- version of the bot. Those bounds live in services/api's zod schemas (P2), not here; the only CHECKs
-- below are the ones a bad value would actually break something with, since a CHECK legacy data can
-- violate is a migration that fails on prod rows.

-- Legacy's `LevelUpNotificationMode` (None/DM/Channel), uppercased per deviation 1 above.
CREATE TYPE social_level_up_notification_mode AS ENUM (
  'NONE',
  'DM',
  'CHANNEL'
);

CREATE TABLE social_guild_settings (
  guild_id                                  TEXT PRIMARY KEY,
  -- These three are legacy's "is this guild configured at all" gate: the bot is fully inert in a guild
  -- until `required_messages`, `required_messages_timespan` and `xp_gain` are all non-NULL. Deliberately
  -- nullable rather than defaulted -- "row exists, not fully configured yet" is a real state the
  -- dashboard flow needs to render, and defaulting them would silently switch XP tracking on for a guild
  -- that only ever touched, say, the notification message.
  --
  -- `required_messages` messages within `required_messages_timespan` seconds earn XP once; the rolling
  -- window itself lives in Redis (`leveling_tracking:`/`leveling_ineligible:` keys), never here.
  required_messages                         INTEGER,
  -- Seconds.
  required_messages_timespan                INTEGER,
  xp_gain                                   INTEGER,
  -- XP curve: total XP required for level n is `required_xp_base + required_xp_multiplier * n(n-1)/2`
  -- (closed form of the triangular series). This formula is frozen for migration fidelity -- changing it
  -- silently re-levels every migrated user.
  required_xp_base                          INTEGER,
  required_xp_multiplier                    INTEGER,
  level_up_notification_mode                social_level_up_notification_mode NOT NULL DEFAULT 'NONE',
  -- Where a 'CHANNEL' notification goes when the message's own channel can't be posted in. The bot
  -- nulls this itself when the fallback turns out to be dead (ported legacy behavior).
  level_up_notification_fallback_channel_id TEXT,
  -- Template supporting `{{ username }}`, `{{ level }}`, `{{ guildName }}` and `{{ earnedRewards }}`.
  -- NULL falls back to the default at render time rather than being baked in here, so the default can
  -- change later without a data migration (same reasoning as `guild_settings.anon_reply_label`).
  level_up_notification_message             TEXT,
  -- Opt-in for the unauthenticated leaderboard page (`/leaderboard/:guildId`). Deliberately *not* an
  -- `ama_sessions.share_token`-style capability: an unguessable link would only make the page unlisted, since
  -- whoever it's handed to can forward it anyway, and the cost of that thin guarantee is a whole parallel
  -- identifier (plus a guildless realtime channel, since the page must not show the viewer a guild snowflake
  -- it already has in its URL). One leaderboard per guild, keyed by the guild -- so this is just on or off.
  -- Off by default: everything the page shows is member activity data.
  public_leaderboard                        BOOLEAN NOT NULL DEFAULT false,

  -- Not style bounds: level derivation walks levels upward while the accumulated requirement is still
  -- covered by the user's XP, so a base of 0 (with any multiplier) or a multiplier of 0 makes the
  -- requirement stop growing and the walk never terminate. Legacy's own command options already
  -- enforced both minimums, so real data satisfies these; a row that doesn't is one that would hang the
  -- bot, and failing the migration loudly on it is the correct outcome.
  CONSTRAINT social_guild_settings_required_xp_base_check
    CHECK (required_xp_base IS NULL OR required_xp_base >= 1),
  CONSTRAINT social_guild_settings_required_xp_multiplier_check
    CHECK (required_xp_multiplier IS NULL OR required_xp_multiplier >= 1)
);

-- Per-guild XP ledger. Guild-first PK (deviation 4): legacy's `@@id([userId, guildId])` order was
-- arbitrary -- every lookup is equality on both -- but guild-first additionally serves guild-scoped
-- scans (the migration's per-guild XP-sum verification, and the leaderboard, which redesign ledger item 5
-- left as a follow-up and which shipped after P4). Same reasoning applies to
-- `social_channels`/`social_roles`/`social_rewards` below.
CREATE TABLE social_users (
  guild_id TEXT NOT NULL,
  user_id  TEXT NOT NULL,
  -- Total XP, with no regard for level calculations -- a level is always derived from this through the
  -- curve above, never stored. INTEGER rather than BIGINT deliberately: postgres.js hands int8 back as a
  -- string (it doesn't fit a JS number), and no plausible amount of XP approaches int4's ceiling.
  xp       INTEGER NOT NULL DEFAULT 0,
  -- Per-user opt-out: this user earns no XP in this guild.
  ignored  BOOLEAN NOT NULL DEFAULT false,

  PRIMARY KEY (guild_id, user_id)
);

-- The leaderboard's only access path: rank order within one guild, which the guild-first PK can't serve
-- (it orders by `user_id`, so ranking means sorting the whole guild every page). `ignored` rows are
-- filtered rather than ranked, but they're a rounding error next to a guild's member count and putting
-- them in the index key would cost more on the write side than the filter saves on the read side.
--
-- `user_id ASC` is part of the key, not decoration: it's the leaderboard's tie-breaker, and ties are the
-- normal case rather than an edge one here -- every member earns the same `xp_gain` per grant, so a guild
-- full of people on their third grant all sit on exactly the same XP. Without it the index orders by `xp`
-- and Postgres re-sorts each tied run to make paging stable.
--
-- Deliberately accepted cost: `xp` is written on the hot path (every XP grant re-indexes the row). That
-- is why this was held back until something actually read in rank order -- now something does, and a
-- leaderboard without it is a full sort of the guild's `social_users` per page view.
CREATE INDEX social_users_guild_id_xp_idx ON social_users (guild_id, xp DESC, user_id ASC);

-- A row here can describe the message's own channel, its parent category, or (for a thread) the thread
-- parent's parent -- the bot resolves both `ignored` and `multiplier` by walking that chain, which is
-- what lets one row silence or boost an entire category.
CREATE TABLE social_channels (
  guild_id   TEXT NOT NULL,
  channel_id TEXT NOT NULL,
  ignored    BOOLEAN NOT NULL DEFAULT false,
  -- NOT NULL DEFAULT 1 (deviation 2). Multiplies the guild's `xp_gain`; stays integral per redesign
  -- ledger item 4 (fractional multipliers change hot-path XP math and are out of port scope).
  multiplier INTEGER NOT NULL DEFAULT 1,

  PRIMARY KEY (guild_id, channel_id),
  CONSTRAINT social_channels_multiplier_check CHECK (multiplier >= 1)
);

-- Role multipliers stack multiplicatively across every configured role the member holds, on top of the
-- channel multiplier.
CREATE TABLE social_roles (
  guild_id   TEXT NOT NULL,
  role_id    TEXT NOT NULL,
  -- NOT NULL DEFAULT 1 (deviation 2), same as `social_channels.multiplier`.
  multiplier INTEGER NOT NULL DEFAULT 1,

  PRIMARY KEY (guild_id, role_id),
  CONSTRAINT social_roles_multiplier_check CHECK (multiplier >= 1)
);

-- Role rewards. One row per rewarded role, so a role can only be a reward for a single level in a guild
-- (legacy's `/reward create` was an upsert per role for exactly this reason).
CREATE TABLE social_rewards (
  guild_id TEXT NOT NULL,
  role_id  TEXT NOT NULL,
  level    INTEGER NOT NULL,
  -- A "clean"/tiered reward: only the *highest* clean reward at or below the member's level is held, so
  -- a new tier replaces the previous one. Non-clean rewards simply accumulate. The bot computes both
  -- sets additively (which roles to add, which superseded clean tiers to remove) rather than rebuilding
  -- the member's whole role set the way legacy did -- see redesign ledger item 2.
  clean    BOOLEAN NOT NULL DEFAULT false,
  -- Free-text staff note: what this role actually grants ("lets them share links across the server with
  -- native automod"), which the role name alone never says. Deliberately **staff-facing only** -- the
  -- dashboard renders it, and services/social-bot never reads it, so `/level` is unaffected. That's the
  -- owner's call and it's load-bearing: moderators write this expecting other moderators to read it, so
  -- surfacing it to members later would retroactively publish notes written in private. Adding a separate
  -- member-visible blurb is the correct move if that's ever wanted, not repurposing this column.
  description TEXT,

  PRIMARY KEY (guild_id, role_id),
  CONSTRAINT social_rewards_level_check CHECK (level >= 0)
);

-- Custom per-guild commands (`/hug`-style): each row is backed by a real Discord guild application
-- command named after it, and renders this stored content when invoked.
--
-- Deviation 3, both halves. The surrogate `id`: legacy keyed these `@@id([guildId, name])`, which makes
-- a rename an identity change and gives the dashboard's edit/delete routes nothing stable to address --
-- the same shape `snippets` (its closest analogue in this schema, down to the `command_id`) already
-- solved with an identity PK plus a `(guild_id, name)` UNIQUE. That UNIQUE also keeps the property the
-- natural key gave the migration: an accidental re-run fails loudly instead of duplicating rows.
CREATE TABLE social_interactions (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id       TEXT NOT NULL,
  -- The guild command this interaction dispatches from. Nullable, where legacy had it NOT NULL (and in
  -- its PK): a command id belongs to an *application*, so every legacy id 404s under the new bot's
  -- application. The migration writes NULL here and the P6 cutover resync assigns real ids -- the exact
  -- lesson ModMail's snippets taught (docs/roadmap/01-architecture.md §8). Dispatch tolerates a stale or
  -- missing id anyway, falling back to a `(guild_id, name)` lookup on the invoked command's name before
  -- declaring the interaction gone. See redesign ledger item 3.
  command_id     TEXT,
  -- Doubles as the Discord command name, hence the guild-wide uniqueness below.
  name           TEXT NOT NULL,
  -- Templated with `{{ author }}` and `{{ targets }}` (the latter only meaningful when `allow_targets`).
  content        TEXT NOT NULL,
  -- Embed color, kept as the string legacy stored rather than the integer Discord wants -- parsing is
  -- the renderer's job, and reinterpreting it here would need a data migration to be sure of the format.
  color          TEXT,
  -- Sent outside the embed, alongside it, when `embed` is on.
  plain_content  TEXT,
  -- Rendered as the embed's image.
  attachment_url TEXT,
  uses           INTEGER NOT NULL DEFAULT 0,
  embed          BOOLEAN NOT NULL DEFAULT false,
  -- Whether the generated command takes user-mention options, which render into `{{ targets }}`.
  allow_targets  BOOLEAN NOT NULL DEFAULT false,

  CONSTRAINT social_interactions_guild_id_name_key UNIQUE (guild_id, name)
);

-- Dispatch's primary lookup. Partial because a row with no command id is only reachable through the
-- `(guild_id, name)` fallback (covered by the UNIQUE above) until a resync gives it one -- which,
-- immediately post-migration, is every row.
--
-- UNIQUE because dispatch resolves an incoming interaction to exactly one row by its command id: two
-- rows sharing one would make it pick nondeterministically, and a command id identifies a single Discord
-- command, so sharing one is never legitimate. Being partial, this constrains nothing about the
-- all-NULL post-migration state.
--
-- Consequence for the resync routine (redesign ledger item 3): clear a guild's `command_id`s first, then
-- write the newly registered ids -- don't update row-by-row in place. A bulk overwrite preserves a
-- command's id when its name is unchanged, so renaming interaction A and creating a new interaction with
-- A's old name hands the new row an id the stale row still holds, and an in-place update order exists
-- that transiently violates this index (which, being an index rather than a constraint, can't be
-- deferred to commit).
CREATE UNIQUE INDEX social_interactions_guild_id_command_id_idx ON social_interactions (guild_id, command_id)
  WHERE command_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- AutoModerator (docs/roadmap/11-automoderator-port.md)
--
-- Additive alongside the still-live legacy deployment, which stays on `postgres-old` until P9. Every table
-- here is prefixed `automoderator_` rather than sharing the bare names its legacy Prisma schema used --
-- `cases`, `tasks`, `reports` are all words the other three products could plausibly want too, and this is
-- one database rather than legacy's four.
-- ---------------------------------------------------------------------------

CREATE TABLE automoderator_guild_settings (
  guild_id     TEXT PRIMARY KEY,
  -- Dry-run: decide and record, but suppress every Discord side effect. A **development affordance only** --
  -- `automoderator-bot`'s `dryRun.ts` ignores this outright when IS_PRODUCTION, so a production guild can
  -- neither be put into it nor stuck in it. That's why there's no env-var layer above this: an operator
  -- switch that only ever reads one way in production would be a switch that lies.
  -- Defaults to on, because the value you get by not thinking about it is the one that can't ban someone in
  -- a real guild from a dev session.
  dry_run      BOOLEAN NOT NULL DEFAULT true,
  -- Where report cards are posted (P3). A plain channel rather than a `automoderator_log_webhooks` row,
  -- unlike every actual log: a report card carries buttons, and `components` on Execute Webhook needs an
  -- application-owned webhook, which the ones the API creates with a bot token are not. Legacy used a plain
  -- channel here too. The cost is that the bot needs Send Messages in the channel, where a log only needs the
  -- token.
  reports_channel_id TEXT,
  -- High-water mark for `automoderator_cases.case_id`, bumped by an atomic
  -- `INSERT ... ON CONFLICT DO UPDATE SET last_case_id = last_case_id + 1 RETURNING` in `caseNumbers.ts`.
  -- Legacy allocated case numbers with a `findFirst(orderBy: caseId desc) + 1` read-then-write inside its
  -- transaction and left a TODO about it: two concurrent creates in one guild could read the same number, and
  -- nothing stopped them, since legacy also had no unique constraint on `(guild_id, case_id)`. A counter column
  -- is the shape `threads.last_local_thread_message_id` already uses here for the same job, and it is correct
  -- across replicas rather than only within one process. Gaps are accepted -- a number reserved for a case whose
  -- Discord call then fails is simply skipped; the guarantee wanted is monotonic and unique, not gapless.
  last_case_id INTEGER NOT NULL DEFAULT 0
);

-- Legacy's `CaseAction`, uppercased to match this schema's other enums (`ama_question_state`,
-- `social_level_up_notification_mode`) -- the same deviation Social recorded, so the P9 migration uppercases.
--
-- The value set is legacy's exactly. What did *not* survive is the mute *mechanism*: a MUTE is now always a
-- native timeout, so legacy's `use_timeouts` flag and its `unmute_roles` role snapshot have no column here (see
-- the port doc's dropped features 16 and 21). The four-week ceiling that comes with timeouts is enforced in the
-- command, not by a CHECK -- `expires_at` also has to be able to hold a legacy row's longer value at P9.
CREATE TYPE automoderator_case_action AS ENUM (
  'WARN',
  'MUTE',
  'UNMUTE',
  'KICK',
  'SOFTBAN',
  'BAN',
  'UNBAN'
);

-- The moderation record: one row per action taken, whether through a command, a filter, or a moderator using
-- Discord's own UI. Everything else in this product either produces cases or reads them.
CREATE TABLE automoderator_cases (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id        TEXT NOT NULL,
  -- The number moderators actually say out loud ("case 42"), sequential per guild and unrelated to `id`.
  -- Allocated from `automoderator_guild_settings.last_case_id`; see that column.
  case_id         INTEGER NOT NULL,
  -- Another case's `case_id` **in the same guild**, not an `id` -- moderators reference the number they can
  -- see. Deliberately not a foreign key: it points at a guild-scoped natural key, and legacy allowed a
  -- reference to a case that was later deleted rather than cascading the deletion outward.
  ref_id          INTEGER,
  target_id       TEXT NOT NULL,
  -- Username snapshot, denormalized on purpose: a case outlives the account it describes, and "who was this"
  -- is the first question asked of a two-year-old ban. Post-pomelo this is a bare username where legacy stored
  -- `name#1234`, so migrated rows keep their discriminator and new ones don't -- it is display text, never a key.
  target_tag      TEXT NOT NULL,
  -- Null for anything no human authored: an automod hit, or a manual action whose audit-log entry could not be
  -- attributed. Legacy left every observed manual action unattributed even when the audit entry named the
  -- moderator; the observer here records it (see `services/automoderator-bot/src/lib/auditObserver.ts`).
  mod_id          TEXT,
  mod_tag         TEXT,
  action_type     automoderator_case_action NOT NULL,
  reason          TEXT,
  -- When the punishment lifts. Written for MUTE (Discord expires the timeout itself) and, from P2, for timed
  -- bans (which need the scheduler to actually lift them). Null means permanent.
  expires_at      TIMESTAMPTZ,
  -- Set by `/case pardon`; a pardoned WARN stops counting toward the ladder and is hidden from `/history`.
  pardoned_by     TEXT,
  -- The mod-log webhook message this case rendered into, so an edit rewrites that embed in place instead of
  -- posting a second one. Null until the log lands, and permanently null for a guild with no mod log configured.
  log_message_id  TEXT,
  -- The case was decided but its Discord side effect was suppressed. Only ever true outside production
  -- (`dryRun.ts` short-circuits), and the reason dry-run still writes rows at all: the ladders P2 adds are
  -- stateful, so a dry run that persisted nothing could not exercise the part most likely to be wrong. Ladder
  -- counting ignores these in live mode so a dev session can't push a real user up a rung.
  dry_run         BOOLEAN NOT NULL DEFAULT false,
  -- Dedupe key for cases this bot files in response to an event rather than a command. Gateway redelivery
  -- after a reconnect is normal, and the audit-log correlation feature 27 does is exactly the shape that
  -- double-fires, so the observer derives a stable key from the audit entry and lets the unique index below
  -- reject the second attempt. Null for command-authored cases, which are already one-per-invocation.
  idempotency_key TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Legacy had no constraint here at all, which is what let its racy allocator produce duplicates.
  CONSTRAINT automoderator_cases_guild_id_case_id_key UNIQUE (guild_id, case_id)
);

-- The case browser's keyset pagination (`ORDER BY id DESC` within a guild). Legacy had **no index on `cases`
-- whatsoever** beyond its primary key, so every history lookup and every dashboard page was a sequential scan;
-- these three exist because that's a bug to fix in the port rather than inherit.
CREATE INDEX automoderator_cases_guild_id_id_idx ON automoderator_cases (guild_id, id DESC);

-- `/history` and the case-detail sidebar's "other cases for this user", both of which are guild + target
-- ordered newest-first.
CREATE INDEX automoderator_cases_guild_id_target_id_idx ON automoderator_cases (guild_id, target_id, id DESC);

-- Partial, because only event-driven cases carry a key and a command-authored case must not collide with
-- anything. Unique rather than plain: this index *is* the idempotency mechanism -- the observer inserts
-- optimistically and treats a 23505 as "already filed", which is race-free in a way a read-then-insert isn't.
CREATE UNIQUE INDEX automoderator_cases_guild_id_idempotency_key_idx
  ON automoderator_cases (guild_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

-- Which log goes where. All four values exist from the start even though P1 only ever writes MOD: the
-- vocabulary is closed and already settled by the port doc (FILTER lands at P5, MESSAGE and USER at P4), and
-- an enum value costs nothing dormant while adding one later is a migration.
CREATE TYPE automoderator_log_type AS ENUM (
  'MOD',
  'FILTER',
  'MESSAGE',
  'USER'
);

-- One webhook per log type per guild, created by the API when a log channel is configured.
--
-- A webhook rather than a plain bot message, carried over from legacy: it survives the bot losing send
-- permission in the channel, it lets the log carry a per-type identity, and the token is a capability that
-- needs no gateway presence -- which is why `services/api` can create it and the bot can post through it.
CREATE TABLE automoderator_log_webhooks (
  guild_id      TEXT NOT NULL,
  log_type      automoderator_log_type NOT NULL,
  -- The channel the webhook posts to, kept alongside the webhook itself because the dashboard renders it and
  -- because case log embeds deep-link to `channels/<guild>/<channel>/<message>`. For a thread target this is
  -- the *parent* channel -- a webhook belongs to the parent and reaches the thread via `thread_id`.
  channel_id    TEXT NOT NULL,
  webhook_id    TEXT NOT NULL,
  -- Encrypted at rest with ENCRYPTION_KEY (AES-256-GCM) via backend-core's `crypt.ts`, the same treatment
  -- `modmail_instances.token` gets and a deliberate departure from legacy, which stored these in plaintext.
  -- A webhook token is a standing capability to post into someone's guild, so a database dump should not carry
  -- a usable one for every configured server.
  webhook_token TEXT NOT NULL,
  -- Set only when the configured target was a thread; forwarded as `?thread_id=` on execute.
  thread_id     TEXT,

  PRIMARY KEY (guild_id, log_type)
);

-- Reports (P3, features 29 and 30). A report is a *request* for moderator attention, which is why it is not a
-- case: it may be dismissed without anything happening, and one report can gather several reporters.
-- Resolving one into a real punishment produces a case and points at it.
CREATE TYPE automoderator_report_state AS ENUM ('OPEN', 'DISMISSED', 'ACTIONED');

-- Where the reported message was, which is a different question from where the report went. Both values exist
-- from the start even though P3 only ever writes GUILD: DM reporting is the next phase and it changes what the
-- card may render (a DM has no jump link staff could ever follow), so the *distinction* has to be storable
-- before there are rows that need it. Same reasoning as `automoderator_log_type` carrying all four values at
-- P1 -- an enum value costs nothing dormant, and adding one later is a migration.
CREATE TYPE automoderator_report_origin AS ENUM ('GUILD', 'DM');

CREATE TABLE automoderator_reports (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Legacy's `reports` table had **no guild column at all**, so its dedupe lookups matched across every guild
  -- the deployment served: one guild acknowledging a user-level report made that user unreportable everywhere.
  -- Not carried forward.
  guild_id          TEXT NOT NULL,
  target_id         TEXT NOT NULL,
  -- Username snapshot, for the same reason `automoderator_cases.target_tag` is one: the row outlives the
  -- account, and a queue entry whose subject can no longer be resolved is unreadable without it.
  target_tag        TEXT NOT NULL,
  origin            automoderator_report_origin NOT NULL DEFAULT 'GUILD',
  -- Null for a report about an account rather than a specific message. Nothing files one at P3 -- both context
  -- menus are message menus, as legacy's were -- but the column is what makes an account-level report
  -- representable, and legacy's schema allowed it too.
  message_id        TEXT,
  -- The reported message's channel, kept so the card can deep-link to it. Null when `message_id` is -- and
  -- deliberately *not* the thing that decides whether a link is rendered, since a DM-origin report has a
  -- channel id staff could never open. `origin` decides that.
  channel_id        TEXT,
  -- Snapshot of what was reported, taken from the interaction's `resolved.messages` payload. Stored rather
  -- than re-fetched because the whole point of a report is that the message may be edited or deleted before a
  -- moderator looks at it -- refetching would show them a message that no longer says what was reported.
  message_content   TEXT,
  -- First attachment's CDN url, rendered as the card embed's image. Discord re-hosts an embed image it is
  -- handed, so the card keeps working after the original url's signature expires; the *dashboard* renders the
  -- same url directly and will therefore show a dead image for an old report. Accepted: the card is the
  -- primary surface and staff act from it.
  message_image_url TEXT,
  state             automoderator_report_state NOT NULL DEFAULT 'OPEN',
  resolved_by       TEXT,
  resolved_at       TIMESTAMPTZ,
  -- The case an ACTIONED report produced -- a guild-scoped `automoderator_cases.case_id`, the number a
  -- moderator can see, not an `id`. Deliberately not a foreign key, for the same reason
  -- `automoderator_cases.ref_id` isn't: it names a guild-scoped natural key, and deleting the case should not
  -- cascade into the report that prompted it.
  case_id           INTEGER,
  -- The card in the reports channel, so dismissing or actioning a report rewrites it in place rather than
  -- posting a second one. The channel is stored alongside because editing a message needs it and the guild's
  -- configured reports channel can change under an already-posted card.
  card_channel_id   TEXT,
  card_message_id   TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- The queue's keyset pagination, mirroring `automoderator_cases_guild_id_id_idx`.
CREATE INDEX automoderator_reports_guild_id_id_idx ON automoderator_reports (guild_id, id DESC);

-- "Everything reported about this account", which the queue offers as a filter for the same reason the case
-- browser does.
CREATE INDEX automoderator_reports_guild_id_target_id_idx
  ON automoderator_reports (guild_id, target_id, id DESC);

-- One report per message per guild, **for all time** rather than only while open. That keeps legacy's useful
-- half -- a message staff already reviewed and dismissed cannot be re-queued by the next person to find it --
-- while dropping the half that was a bug (see `guild_id` above). Also the lookup the report path does before
-- deciding between "add a reporter" and "open a new report", so it is unique rather than plain.
CREATE UNIQUE INDEX automoderator_reports_guild_id_message_id_idx
  ON automoderator_reports (guild_id, message_id)
  WHERE message_id IS NOT NULL;

-- Account-level reports dedupe only while open, unlike message ones: "this account, again" is a legitimate
-- new report once staff have closed the last one, whereas "this exact message, again" is not.
CREATE UNIQUE INDEX automoderator_reports_guild_id_target_id_open_idx
  ON automoderator_reports (guild_id, target_id)
  WHERE message_id IS NULL AND state = 'OPEN';

-- Who asked, and why. Separate from the report because the second person to report something is agreeing with
-- the first, not filing a new item -- collapsing them is what stops a busy channel burying its own queue.
CREATE TABLE automoderator_reporters (
  report_id    INTEGER NOT NULL REFERENCES automoderator_reports (id) ON DELETE CASCADE,
  reporter_id  TEXT NOT NULL,
  reporter_tag TEXT NOT NULL,
  reason       TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Doubles as the "you have already reported this" check.
  PRIMARY KEY (report_id, reporter_id)
);

-- Canned reasons offered by the reason-picking context menu, so a member reporting something picks from the
-- vocabulary the guild's staff actually triage by instead of typing prose.
--
-- The chosen text is *copied* into `automoderator_reporters.reason` rather than referenced, so editing or
-- deleting a preset never rewrites what somebody already said.
CREATE TABLE automoderator_report_presets (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id TEXT NOT NULL,
  reason   TEXT NOT NULL,

  -- Discord's select menu caps at 25 options, which the API enforces; this only stops the same reason being
  -- listed twice, which would render two identical rows a reporter can't tell apart.
  CONSTRAINT automoderator_report_presets_guild_id_reason_key UNIQUE (guild_id, reason)
);

CREATE INDEX automoderator_report_presets_guild_id_idx ON automoderator_report_presets (guild_id, id);
