-- Declarative schema (source of truth for `atlas migrate diff`).
--
-- Naming convention: snake_case tables/columns, mapped to camelCase JS via the
-- `postgres.camel` transform passed to `createDb()` (SimplyChords' convention —
-- see docs/roadmap/02-foundation.md Part A step 2 for the decision writeup).
--
-- Reproduces the 6 current Prisma models 1:1 (see prisma/schema.prisma and
-- docs/roadmap/01-architecture.md §5): Experiment, ExperimentOverride,
-- DashboardGrant, AMASession, AMAPromptData, AMAQuestion (+ AMAQuestionState).
--
-- Note: Prisma's `@updatedAt` on AMAQuestion.updatedAt was a Prisma-client-side
-- behavior (set on every client `.update()` call), not a DB trigger. There is no
-- trigger reproducing it here — the route migration (raw SQL, see #128) is
-- responsible for setting `updated_at = now()` explicitly on updates.

CREATE TABLE experiments (
  name        TEXT PRIMARY KEY,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ,
  range_start INTEGER NOT NULL,
  range_end   INTEGER NOT NULL
);

CREATE TABLE experiment_overrides (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id        TEXT NOT NULL,
  experiment_name TEXT NOT NULL REFERENCES experiments (name) ON DELETE CASCADE,

  CONSTRAINT experiment_overrides_guild_id_experiment_name_key UNIQUE (guild_id, experiment_name)
);

CREATE INDEX experiment_overrides_experiment_name_idx ON experiment_overrides (experiment_name);

CREATE TABLE dashboard_grants (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id       TEXT NOT NULL,
  user_id        TEXT NOT NULL,
  created_by_id  TEXT NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT dashboard_grants_guild_id_user_id_key UNIQUE (guild_id, user_id)
);

CREATE TABLE ama_sessions (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id                 TEXT NOT NULL,
  queue_id                 TEXT,
  title                    TEXT NOT NULL,
  -- Nullable since #316: NULL means this AMA publishes nowhere on Discord, and the public answers page
  -- (`share_token` below) is the only surface an answer ever reaches. Every path that would otherwise
  -- post/edit/delete an answers-channel message skips the Discord call and leaves
  -- `ama_questions.answers_message_id` null; the question still transitions to 'ASKED' with an
  -- `asked_at`, which is what the public page reads. Switching an existing AMA either way only affects
  -- questions sent afterwards -- already-posted messages are left alone rather than retro-deleted.
  answers_channel_id       TEXT,
  prompt_channel_id        TEXT NOT NULL,
  -- Max files on the submit modal. Must be 0 when the AMA has no Discord message surface at all
  -- (answers_channel_id IS NULL AND queue_id IS NULL) -- attachments are never persisted here, every
  -- consumer reads them back off whichever live Discord message currently shows the question (see
  -- services/api's questions/util.ts `resolveQuestionAttachments`), so with no message they'd be
  -- silently dropped. Enforced in services/api (createAMA/updateAMA) rather than by a CHECK, so the
  -- dashboard can surface *why* the field is disabled instead of failing on a constraint violation.
  allowed_question_uploads INTEGER NOT NULL DEFAULT 2,
  ended                    BOOLEAN NOT NULL DEFAULT false,
  -- Optional automated close date (#290), settable at creation and editable retroactively (while the AMA is
  -- still active -- updateAMA.ts already rejects any edit once `ended`) via services/ama-bot's
  -- scheduledCloseSweep.ts, which flips `ended` the same way `/ama end` does once this lapses.
  scheduled_close_at       TIMESTAMPTZ,
  -- Decouples approving a question from posting it (#293 follow-up, "Tommy" AMA question management).
  -- Off (default): unchanged behavior, approval == posting. On: approval only sets state to APPROVED,
  -- an answer can be prepared ahead of time (the dashboard's answer editor), and posting to
  -- answers_channel_id only happens via the dashboard's explicit Send action.
  prepared_answers_enabled BOOLEAN NOT NULL DEFAULT false,
  -- Splits "does review exist" from "does it have a Discord channel" -- lets review be enabled but
  -- dashboard-only (no queue message posted anywhere). Review now has one unified pool of reviewers
  -- (mods in Discord and/or dashboard, plus any configured `guest_ids` via the dashboard), so a
  -- dash-only review stage always has somewhere to be handled. Backfilled for existing rows as
  -- `(mod_queue_id IS NOT NULL)`, which exactly preserves prior behavior: a stage that was never
  -- configured stays fully skipped, not silently reinterpreted.
  -- Submission (prompt_channel_id) stays deliberately excluded from this pattern -- it's the only entry
  -- point a question can arrive through (the prompt message's "Submit a question" button), so there'd be
  -- nothing left to submit *with*. Publishing used to be excluded for the same "cannot be dash-only"
  -- reason but no longer is; see answers_channel_id above (#316).
  review_enabled           BOOLEAN NOT NULL DEFAULT false,
  -- Opaque id backing the public, unauthenticated read-only answers page (`/ama-answers/:shareToken`).
  -- Generated unconditionally at creation (see createAMA.ts) -- pre-existing rows were backfilled a
  -- generated value in the same migration that added this column.
  share_token              TEXT NOT NULL UNIQUE,
  -- Known guest user ids for this AMA (freeform, editable retroactively). Guests get scoped dashboard
  -- access to this AMA's Questions/Analytics pages regardless of their general dashboard/guild-manage
  -- status (see services/api's `'or-ama-guest'` auth path) and can act on the queue exactly like a mod
  -- (approve/deny/merge/prepare+send answers/tag) -- plus back the "answered by" picker in the
  -- dashboard's answer editor. Empty by default, in which case the picker falls back to its original
  -- free-text/default-to-self behavior and there are no non-manager dashboard users for this AMA.
  guest_ids                TEXT[] NOT NULL DEFAULT '{}',
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT ama_sessions_review_enabled_check CHECK (review_enabled OR queue_id IS NULL)
);

CREATE TABLE ama_prompt_data (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ama_id            INTEGER NOT NULL UNIQUE REFERENCES ama_sessions (id) ON DELETE CASCADE,
  prompt_message_id TEXT NOT NULL UNIQUE,
  prompt_json_data  TEXT NOT NULL
);

-- 'ASKED' (#293 follow-up) is the only state meaning "posted to the answers channel" -- 'APPROVED'
-- universally means "approved, not necessarily posted yet" now. When `prepared_answers_enabled` is
-- off, the approve paths set 'ASKED' directly (posting immediately, same as the old 'APPROVED'
-- behavior); when on, they hold at 'APPROVED' and only the dashboard's Send action produces 'ASKED'.
-- Mod review and guest review used to be two sequential stages ('PENDING_MOD_REVIEW' then
-- 'PENDING_GUEST_REVIEW'), with a separate read-only 'FLAGGED' dead-end reachable only from mod review.
-- Both are gone: guests now review the same single queue via dashboard access instead of a dedicated
-- Discord channel, and flagging (a dead-end with no forward path) was removed outright.
CREATE TYPE ama_question_state AS ENUM (
  'PENDING_REVIEW',
  'APPROVED',
  'DENIED',
  'ASKED'
);

CREATE TABLE ama_questions (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ama_id                   INTEGER NOT NULL REFERENCES ama_sessions (id) ON DELETE CASCADE,
  author_id                TEXT NOT NULL,
  state                    ama_question_state NOT NULL DEFAULT 'PENDING_REVIEW',
  content                  TEXT NOT NULL,
  queue_message_id         TEXT,
  answers_message_id       TEXT,
  -- Answer fields (#293 follow-up), written from the dashboard only -- the bot-side "Add Answer" modal
  -- this comment used to also name was never actually built (#200, still open). Populated ahead of Send
  -- when `ama_sessions.prepared_answers_enabled` is on, and since #327 also editable afterwards, on an
  -- already-'ASKED' question (which re-renders the live answers-channel message rather than reposting).
  -- All nullable: a question can reach 'APPROVED' with no answer prepared yet, and an AMA answered live
  -- on stream may never record one at all.
  answer_content           TEXT,
  answer_image_url         TEXT,
  answered_by_id           TEXT,
  answered_at              TIMESTAMPTZ,
  -- Set once, on the transition to 'ASKED' (every path that posts to the answers channel writes it).
  -- The public answers page used to read `updated_at` for this, which stopped being correct once #327
  -- made an already-sent answer editable -- fixing a typo months later would have moved the question's
  -- displayed "asked at" to today. Nullable: non-'ASKED' rows never have one, and rows predating this
  -- column were backfilled from `updated_at` (the best approximation available).
  asked_at                 TIMESTAMPTZ,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Referenced by ama_question_tag_assignments' composite FK below, so a tag assignment's own ama_id
  -- is guaranteed to match the question it's attached to, not just the tag.
  CONSTRAINT ama_questions_id_ama_id_key UNIQUE (id, ama_id)
);

CREATE INDEX ama_questions_ama_id_idx ON ama_questions (ama_id);

-- Duplicate-merge target (#293 follow-up): merging question A into B deletes A and adds an
-- `ama_question_askers` row for B recording A's author. B's own `author_id` *can* land in here when
-- someone asks twice and both of their questions get merged together, so anything counting "other
-- people who asked this" has to filter it back out (see `countExtraAskers`). The live Discord embed
-- shows a bare count of those askers (#326) and never their names -- who they are stays a
-- dashboard-only detail; `content` preserves A's original
-- question text for the dashboard's merged-duplicate display, snapshotted at merge time since the
-- row it came from is deleted. Nullable, and deliberately never backfilled for rows merged before
-- this column existed -- that content was already destroyed by the delete, unrecoverably.
CREATE TABLE ama_question_askers (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id INTEGER NOT NULL REFERENCES ama_questions (id) ON DELETE CASCADE,
  author_id   TEXT NOT NULL,
  content     TEXT,
  merged_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT ama_question_askers_question_id_author_id_key UNIQUE (question_id, author_id)
);

CREATE INDEX ama_question_askers_question_id_idx ON ama_question_askers (question_id);

-- Per-AMA-session freeform mod-side tags (#293 follow-up) -- dashboard-only, not reusable across
-- sessions (genuinely temporary, scoped to a single AMA's lifetime).
CREATE TABLE ama_question_tags (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ama_id     INTEGER NOT NULL REFERENCES ama_sessions (id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT ama_question_tags_ama_id_name_key UNIQUE (ama_id, name),
  -- Referenced by ama_question_tag_assignments' composite FK below, so a tag assignment's own ama_id
  -- is guaranteed to match the tag it's attached to, not just the question.
  CONSTRAINT ama_question_tags_id_ama_id_key UNIQUE (id, ama_id)
);

CREATE INDEX ama_question_tags_ama_id_idx ON ama_question_tags (ama_id);

-- ama_id is redundant with both question_id -> ama_questions.ama_id and tag_id ->
-- ama_question_tags.ama_id individually, but carrying it here lets both composite FKs below pin it to
-- the *same* value on both sides -- which is what actually rules out a tag from AMA A ever getting
-- assigned to a question in AMA B. Set by the application at insert time (see updateQuestion.ts),
-- always equal to the (already-validated-matching) ama_id of both the question and the tag.
CREATE TABLE ama_question_tag_assignments (
  question_id INTEGER NOT NULL,
  tag_id      INTEGER NOT NULL,
  ama_id      INTEGER NOT NULL,

  PRIMARY KEY (question_id, tag_id),
  CONSTRAINT ama_question_tag_assignments_question_fkey FOREIGN KEY (question_id, ama_id)
    REFERENCES ama_questions (id, ama_id) ON DELETE CASCADE,
  CONSTRAINT ama_question_tag_assignments_tag_fkey FOREIGN KEY (tag_id, ama_id)
    REFERENCES ama_question_tags (id, ama_id) ON DELETE CASCADE
);

CREATE INDEX ama_question_tag_assignments_tag_id_idx ON ama_question_tag_assignments (tag_id);
CREATE INDEX ama_question_tag_assignments_ama_id_idx ON ama_question_tag_assignments (ama_id);

-- ModMail (M5, ticket-system rebuild — see docs/roadmap/06-modmail-port.md and issue #152).
--
-- Reproduces the 9 carried-forward models from `ChatSift/ModMail`'s `prisma/schema.prisma`
-- (GuildSettings, Snippet, SnippetUpdates, Thread, ThreadMessage, ScheduledThreadClose, Block,
-- ThreadOpenAlert, ThreadReplyAlert), mostly 1:1, plus two new models (Category, TicketPanel)
-- and a join table (TicketPanelCategory) for the new create-flow.
--
-- Design decisions confirmed 2026-07-23 (owner sign-off, see issue #152 discussion) that shape
-- this section:
--   - Category routing is forum-tag-only: every guild has a single mod forum
--     (guild_settings.mod_forum_id); categories map to a tag within it (categories.forum_tag_id),
--     not a separate forum channel per category.
--   - No staff-role concept was added. The mention/user-ID auto-embed QOL feature (bot-side, not
--     a schema concern) only fires on relayed *user* messages, never staff replies — decided by
--     checking thread_messages.staff_id/user_id on the message being relayed, not by a role.
--   - Multiple ticket panels per guild are expected, each scoped to a subset of a guild's
--     categories chosen at panel-creation time — hence ticket_panel_categories.
--
-- threads.channel_id (old Prisma model) is renamed to mod_thread_id here, disambiguating it from
-- the new user_channel_id now that a thread has two Discord-channel concepts (mod-forum side vs.
-- the user's side, panel private thread or DM channel). Free to do since this table has no prior
-- rows in the new schema.

-- Registry of branded, single-guild ModMail deployments (#216). A row here is what makes a guild
-- "owned" by a custom instance: the public modmail-bot deployment no-ops for any guild listed here,
-- and services/api routes every Discord call for that guild through this instance's token instead of
-- MODMAIL_BOT_TOKEN. Rows are inserted by hand (see docs/workflow.md) alongside adding the matching
-- docker-compose service -- there is deliberately no API/dashboard CRUD for this table, since it
-- holds a live bot token. See docs/roadmap/01-architecture.md §8 for the full design.
CREATE TABLE modmail_instances (
  -- Slug, matched against the deployment's own MODMAIL_INSTANCE_ID env var. Stable; renaming one
  -- means redeploying the service that carries it.
  id         TEXT PRIMARY KEY,
  -- One instance per guild, enforced here rather than in application code -- the whole ownership
  -- model in docs/roadmap/01-architecture.md §8 rests on this being unambiguous.
  guild_id   TEXT NOT NULL UNIQUE,
  -- The custom bot application's token, encrypted at rest with ENCRYPTION_KEY (AES-256-GCM), same
  -- key the JWT signing path already uses. Encrypted rather than plain because a Postgres dump or a
  -- backup snapshot would otherwise carry live bot credentials for every partner.
  token      TEXT NOT NULL,
  -- Display name shown in place of "ModMail" throughout this guild's dashboard.
  label      TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE guild_settings (
  guild_id                 TEXT PRIMARY KEY,
  mod_forum_id             TEXT,
  default_greeting_message TEXT,
  farewell_message         TEXT,
  simple_mode              BOOLEAN NOT NULL DEFAULT false,
  alert_role_id            TEXT,
  -- Author label shown on anonymous staff replies (services/modmail-bot's lib/relay.ts), supports a
  -- `{{ guildName }}` placeholder. NULL falls back to the "{{ guildName }} Team" default at render time
  -- rather than being baked in here, so the default can change later without a data migration.
  anon_reply_label         TEXT,
  -- How many tickets a single user may have open at once in this guild, summed across all categories.
  -- Enforced by services/modmail-bot at ticket-creation time (lib/threads.ts's
  -- countActiveTicketsForUser), not a DB constraint, since it's a soft business rule checked
  -- alongside a Discord API call, not something the write itself can violate.
  max_concurrent_threads   INTEGER NOT NULL DEFAULT 1,
  -- How long, after a ticket closes, before the user's private thread is actually deleted ("nuked") --
  -- see `scheduled_thread_nukes` below. The thread is locked (but deliberately left unarchived, see
  -- services/modmail-bot's `lib/threadClose.ts`) immediately on close regardless. NULL (the default)
  -- means "never nuke" -- an explicit opt-in is required to schedule deletion at all; when opted out,
  -- the thread just sits locked until Discord's own inactivity auto-archive eventually catches it.
  nuke_delay_minutes       INTEGER,
  -- Whether the greeting (category's, falling back to default_greeting_message) is posted before the
  -- user's own opener message is relayed to staff, instead of after. Defaults to false (after) --
  -- matching prod ChatSift/ModMail's existing behavior of relay-then-greet.
  greeting_before_opener   BOOLEAN NOT NULL DEFAULT false,
  -- Consent toggle for recording full message content into `thread_message_content` (see below) --
  -- defaults to false since capturing every reply and surrounding message in a ticket is a real privacy
  -- decision, not a default a guild should be opted into silently. `enabled_by`/`enabled_at` form an
  -- audit trail of who opted in and when; services/api's updateConfig.ts only sets them on the
  -- false->true transition and deliberately leaves them populated after a later disable (see #261).
  record_thread_content                  BOOLEAN NOT NULL DEFAULT false,
  record_thread_content_enabled_by       TEXT,
  record_thread_content_enabled_at       TIMESTAMPTZ,
  -- Whether this guild's ModMail runs on the pre-M5 DM front door instead of ticket panels (#216).
  -- Only meaningful for a guild with a modmail_instances row -- the public deployment never reads it,
  -- and services/api rejects setting it true for a guild with no custom instance. When on, ticket
  -- panels go inert (see the create-ticket component) and the panel-specific settings below stop
  -- applying, but nothing about them is deleted: flipping this back off restores the panel flow as-is.
  dm_mode                                BOOLEAN NOT NULL DEFAULT false,

  CONSTRAINT guild_settings_max_concurrent_threads_check CHECK (max_concurrent_threads >= 1),
  CONSTRAINT guild_settings_nuke_delay_minutes_check CHECK (nuke_delay_minutes IS NULL OR nuke_delay_minutes >= 1)
);

CREATE TABLE categories (
  id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id               TEXT NOT NULL,
  name                   TEXT NOT NULL,
  emoji                  TEXT,
  description            TEXT,
  greeting_message       TEXT,
  forum_tag_id           TEXT,
  sort_order             INTEGER NOT NULL DEFAULT 0,
  -- Per-category override of guild_settings.max_concurrent_threads, for guilds that want to cap a
  -- specific category (e.g. "Bug Reports") tighter than their general limit. NULL means "inherit the
  -- guild's general limit" -- this is the "default" the feature spec means, not a value copied in at
  -- category-creation time, so it keeps tracking the guild setting if that changes later. Must be
  -- <= guild_settings.max_concurrent_threads; enforced at write time by services/api (createCategory/
  -- updateCategory) and defensively re-clamped at read time by services/modmail-bot
  -- (categorySelect.ts) in case the guild setting was lowered after this was set.
  max_concurrent_threads INTEGER,

  CONSTRAINT categories_guild_id_name_key UNIQUE (guild_id, name),
  CONSTRAINT categories_max_concurrent_threads_check CHECK (max_concurrent_threads IS NULL OR max_concurrent_threads >= 1)
);

CREATE INDEX categories_guild_id_idx ON categories (guild_id);

-- Tag-based routing (see comment above) is ambiguous if two categories in the same guild share a
-- forum tag; partial (forum_tag_id nullable, since a category can be unconfigured) unique index
-- enforces one category per tag per guild.
CREATE UNIQUE INDEX categories_guild_id_forum_tag_id_key ON categories (guild_id, forum_tag_id) WHERE forum_tag_id IS NOT NULL;

CREATE TABLE ticket_panels (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id        TEXT NOT NULL,
  channel_id      TEXT NOT NULL,
  message_id      TEXT NOT NULL UNIQUE,
  panel_json_data TEXT NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ticket_panels_guild_id_idx ON ticket_panels (guild_id);

CREATE TABLE ticket_panel_categories (
  ticket_panel_id INTEGER NOT NULL REFERENCES ticket_panels (id) ON DELETE CASCADE,
  category_id     INTEGER NOT NULL REFERENCES categories (id) ON DELETE CASCADE,

  PRIMARY KEY (ticket_panel_id, category_id)
);

CREATE INDEX ticket_panel_categories_category_id_idx ON ticket_panel_categories (category_id);

CREATE TABLE threads (
  id                            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id                      TEXT NOT NULL,
  mod_thread_id                 TEXT NOT NULL,
  user_id                       TEXT NOT NULL,
  created_by_id                 TEXT NOT NULL,
  created_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
  closed_by_id                  TEXT,
  closed_at                     TIMESTAMPTZ,
  last_local_thread_message_id  INTEGER NOT NULL DEFAULT 0,
  category_id                   INTEGER REFERENCES categories (id) ON DELETE SET NULL,
  -- The Discord channel the bot relays a user's side of the conversation through -- a private thread
  -- for the M5 panel flow ('panel' origin below), or the opener's DM channel for DM mode (#216, P4).
  -- Named generically (not "...thread_id") because it isn't always a thread; a DM channel id is stable
  -- per (user, bot application) pair, which is what lets the relay/edit/delete-sync/`/reply` code work
  -- unchanged for both origins -- see docs/roadmap/01-architecture.md §8.
  user_channel_id                TEXT,
  -- How this ticket was opened. 'panel' is the M5 flow (user_channel_id is a real private thread this
  -- bot created and may lock/delete); 'dm' means user_channel_id is the opener's DM channel id, which
  -- must never be locked, archived or deleted. Only 'dm' is possible for a guild running DM mode
  -- (guild_settings.dm_mode); every other ticket is 'panel'.
  origin                        TEXT NOT NULL DEFAULT 'panel',
  -- Which legacy migration run produced this row; NULL for a natively created ticket. Written by
  -- packages/private/db/src/scripts/migrateLegacyModmail.ts's --source flag. Replaces the inferential
  -- "origin = 'dm' AND user_channel_id IS NULL" predicate that script used to identify its own rows,
  -- which could neither tell two legacy sources apart (so migrating one blocked every later run) nor
  -- distinguish a migrated row from a natively created DM-mode ticket with a missing channel id.
  migration_source              TEXT,

  CONSTRAINT threads_origin_check CHECK (origin IN ('panel', 'dm'))
);

CREATE INDEX threads_guild_id_idx ON threads (guild_id);
CREATE INDEX threads_category_id_idx ON threads (category_id);
-- Both looked up on every relayed message/reply command in services/modmail-bot: user_channel_id to
-- find the ticket a private-thread/DM message belongs to, mod_thread_id to find the ticket a /reply or
-- /reply-q command was run in.
CREATE INDEX threads_user_channel_id_idx ON threads (user_channel_id) WHERE user_channel_id IS NOT NULL;
CREATE INDEX threads_mod_thread_id_idx ON threads (mod_thread_id);
-- Back the two concurrent-thread-limit counts in `lib/threads.ts`, both partial on
-- `closed_at IS NULL` since a closed ticket never counts toward either limit and closed rows vastly
-- outnumber open ones over a guild's lifetime. `countActiveTicketsForUser` (the general, guild-wide
-- limit, checked on every ticket-panel click) filters on guild + user only, matching the first index
-- below; `countOpenThreadsForUserInCategory` (the per-category limit, checked on every category pick)
-- additionally filters on `category_id`, matching the second, wider index instead.
CREATE INDEX threads_guild_id_user_id_open_idx ON threads (guild_id, user_id) WHERE closed_at IS NULL;
CREATE INDEX threads_guild_id_user_id_category_id_open_idx ON threads (guild_id, user_id, category_id) WHERE closed_at IS NULL;
-- Only ever read by migrateLegacyModmail.ts (its re-run guard and every target-side --verify count),
-- and partial because natively created rows -- the overwhelming majority -- leave it NULL.
CREATE INDEX threads_migration_source_idx ON threads (migration_source) WHERE migration_source IS NOT NULL;

-- Tracks a ticket from the moment its private thread is created (services/modmail-bot's
-- createTicket.ts for a no-category panel, categorySelect.ts once a category's been picked) until
-- finishTicketCreation actually inserts a `threads` row for it. The Redis-side PendingTicketStore (same
-- TTL) tracks this same window for routing incoming events, but a Redis key TTL alone gives nothing to
-- act on when it lapses -- this table is the durable side a periodic sweep polls to delete private
-- threads whose setup was abandoned (e.g. the user never sent an opening message), and also what
-- `countActiveTicketsForUser`/`countOpenThreadsForUserInCategory` count as "already holding a slot" for
-- tickets still mid-setup. `category_id` is NULL for a no-category panel's pending ticket, same meaning
-- as `threads.category_id`.
CREATE TABLE pending_tickets (
  private_thread_id TEXT PRIMARY KEY,
  guild_id          TEXT NOT NULL,
  user_id           TEXT NOT NULL,
  category_id       INTEGER REFERENCES categories (id) ON DELETE SET NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Backs `countActiveTicketsForUser`'s pending-ticket half of the count (see above).
CREATE INDEX pending_tickets_guild_id_user_id_idx ON pending_tickets (guild_id, user_id);
-- Backs `countOpenThreadsForUserInCategory`'s pending-ticket half of the count -- without this, a
-- category pick made while an earlier pick for the *same* category is still pending (private thread
-- created, opening message not sent yet, so no `threads` row exists for it either) wouldn't be counted
-- against that category's limit, letting a burst of picks blow past it the same way
-- `countActiveTicketsForUser`'s own pending half prevents for the general limit.
CREATE INDEX pending_tickets_guild_id_user_id_category_id_idx ON pending_tickets (guild_id, user_id, category_id);

CREATE TABLE thread_messages (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_thread_message_id  INTEGER NOT NULL,
  guild_id                 TEXT NOT NULL,
  thread_id                INTEGER NOT NULL REFERENCES threads (id) ON DELETE CASCADE,
  user_id                  TEXT NOT NULL,
  -- NULL for an `is_internal` row -- internal chatter never crosses into the user's private thread, so
  -- there's no corresponding message on that side to point at (unlike a user message or a `/reply`'s
  -- relayed copy, both of which always have one).
  user_message_id          TEXT,
  staff_id                 TEXT,
  guild_message_id         TEXT NOT NULL,
  anon                     BOOLEAN NOT NULL DEFAULT false,
  -- True for a plain message posted directly in the mod-forum thread (mod-to-mod discussion), as opposed
  -- to a user message relayed in or a `/reply`/`/reply-q` log copy -- never part of the user-facing
  -- exchange, so the dashboard renders it visually set apart from the actual conversation (#261).
  is_internal              BOOLEAN NOT NULL DEFAULT false,
  -- True for an automated message the bot itself posted (the opening greeting, `lib/ticketCreation.ts`'s
  -- `sendGreeting`; the closing farewell, `lib/threadClose.ts`'s `postFarewellMessage`) -- neither has a
  -- real "sender" the way every other row does (a user's own message, or a staff member's reply/internal
  -- note), so the dashboard needs to tell these apart from both to avoid misattributing them to whichever
  -- of `user_id`/`staff_id` this row happens to carry. `staff_id` is still populated when a farewell is
  -- attributed (non-anon) to the closing staffer -- `NULL` here covers both the greeting (never has an
  -- actor) and an anonymized farewell. Only ever inserted when recording is enabled, same as `is_internal`
  -- (see `insertThreadMessage`'s own doc comment) -- an unrecorded system row would carry zero information.
  is_system                BOOLEAN NOT NULL DEFAULT false,
  -- Set by `lib/userMessageLifecycle.ts`'s `MessageDelete` handler when the user deletes their own
  -- message client-side -- display-only (Phase 3, #261): the row and its `thread_message_content` are
  -- never touched by a user-side delete (see that table's own doc comment), this just lets the dashboard
  -- show a "deleted" badge alongside content that's still fully readable. Never set for a `/reply`-relayed
  -- or `is_internal` row -- those have their own, asymmetric true-delete handling instead.
  deleted_at               TIMESTAMPTZ,

  CONSTRAINT thread_messages_thread_id_local_thread_message_id_key UNIQUE (thread_id, local_thread_message_id)
);

CREATE INDEX thread_messages_thread_id_idx ON thread_messages (thread_id);

-- Sidecar to `thread_messages`, 1:1, same PK-is-FK shape as `scheduled_thread_closes`/
-- `scheduled_thread_nukes` below -- keeps the load-bearing `thread_messages` table lean while giving
-- recorded content its own lifecycle. Only written by services/modmail-bot's `insertThreadMessage` when
-- `guild_settings.record_thread_content` is on for the guild at relay time (see #261); a message with no
-- row here means it predates recording being enabled (or recording was never turned on), which the
-- dashboard thread view renders as a "not recorded" placeholder rather than backfilling or guessing.
CREATE TABLE thread_message_content (
  thread_message_id            INTEGER PRIMARY KEY REFERENCES thread_messages (id) ON DELETE CASCADE,
  content                      TEXT NOT NULL DEFAULT '',
  replied_to_thread_message_id INTEGER REFERENCES thread_messages (id) ON DELETE SET NULL,
  is_forwarded                 BOOLEAN NOT NULL DEFAULT false,
  attachments                  JSONB NOT NULL DEFAULT '[]', -- [{ url, filename, contentType, size }]
  stickers                     JSONB NOT NULL DEFAULT '[]', -- [{ id, name, formatType }]
  recorded_at                  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX thread_message_content_replied_to_idx ON thread_message_content (replied_to_thread_message_id)
  WHERE replied_to_thread_message_id IS NOT NULL;

-- One row per prior version of a `thread_message_content.content`, oldest edits first by `id` -- same
-- "archive the old value before overwriting" shape as `snippet_updates` below, written by
-- `lib/threads.ts`'s `updateRecordedMessageContent` (Phase 3, #261) instead of the blind overwrite it used
-- to do. No `edited_by` column -- unlike a snippet edit (staff-driven), a recorded message's editor is
-- always that message's own author, already known via `thread_messages.user_id`/`staff_id`.
CREATE TABLE thread_message_content_edits (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_message_id  INTEGER NOT NULL REFERENCES thread_message_content (thread_message_id) ON DELETE CASCADE,
  edited_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  old_content        TEXT NOT NULL
);

CREATE INDEX thread_message_content_edits_thread_message_id_idx ON thread_message_content_edits (thread_message_id);

CREATE TABLE scheduled_thread_closes (
  thread_id       INTEGER PRIMARY KEY REFERENCES threads (id) ON DELETE CASCADE,
  scheduled_by_id TEXT NOT NULL,
  silent          BOOLEAN NOT NULL DEFAULT false,
  -- Whether the farewell message this schedule eventually posts should be anonymous ("{guildName}
  -- Team") instead of attributed to scheduled_by_id -- mirrors /close now's anon option (and
  -- /reply's), see services/modmail-bot's lib/threadClose.ts. Attributed is the default, matching
  -- staff replies.
  anon            BOOLEAN NOT NULL DEFAULT false,
  close_at        TIMESTAMPTZ NOT NULL
);

-- A closed ticket's private thread is locked immediately (services/modmail-bot's `lib/threadClose.ts`)
-- but not deleted outright -- a row here is what a periodic sweep (`lib/threadNukeSweep.ts`) polls to
-- actually delete it once `guild_settings.nuke_delay_minutes` has passed. Only written when that column
-- is non-NULL (deletion is opt-in); a guild that never opts in simply never gets a row. Cascades with
-- `threads` since there's nothing left to nuke if the ticket row itself is gone.
CREATE TABLE scheduled_thread_nukes (
  thread_id INTEGER PRIMARY KEY REFERENCES threads (id) ON DELETE CASCADE,
  nuke_at   TIMESTAMPTZ NOT NULL
);

CREATE TABLE blocks (
  user_id    TEXT NOT NULL,
  guild_id   TEXT NOT NULL,
  expires_at TIMESTAMPTZ,

  PRIMARY KEY (user_id, guild_id)
);

CREATE TABLE thread_open_alerts (
  guild_id TEXT NOT NULL,
  user_id  TEXT NOT NULL,

  PRIMARY KEY (guild_id, user_id)
);

CREATE TABLE thread_reply_alerts (
  thread_id INTEGER NOT NULL REFERENCES threads (id) ON DELETE CASCADE,
  user_id   TEXT NOT NULL,

  PRIMARY KEY (thread_id, user_id)
);

-- Note: Prisma's `@updatedAt` on Snippet.lastUpdatedAt was client-side (set on every `.update()`
-- call), not a DB trigger — same caveat as AMAQuestion.updatedAt above. Whatever route/service
-- code updates a snippet's content is responsible for setting `last_updated_at = now()` itself.
CREATE TABLE snippets (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id            TEXT NOT NULL,
  command_id          TEXT NOT NULL,
  created_by_id       TEXT NOT NULL,
  name                TEXT NOT NULL,
  content             TEXT NOT NULL,
  attachment_url      TEXT,
  attachment_filename TEXT,
  times_used          INTEGER NOT NULL DEFAULT 0,
  last_used_at        TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT snippets_guild_id_name_key UNIQUE (guild_id, name),
  -- Backstop for the API's own validation (services/api's updateSnippet.ts clears attachment_filename
  -- whenever attachment_url is cleared) -- a filename with no URL to attach it to is meaningless.
  CONSTRAINT snippets_attachment_filename_requires_url_check CHECK (attachment_filename IS NULL OR attachment_url IS NOT NULL)
);

-- One row per edit, holding the *complete* prior state of every editable snippet field (#324) rather
-- than only the fields that changed -- which field(s) a given revision actually changed is derived at
-- read time by diffing consecutive snapshots (services/api's getSnippetUpdates.ts), so there's no
-- denormalized "changed fields" column that could ever disagree with the snapshots it describes.
-- Storing only the changed fields would also be ambiguous on the two nullable attachment columns,
-- where NULL would mean both "was unset" and "untouched by this edit".
CREATE TABLE snippet_updates (
  id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snippet_id              INTEGER NOT NULL REFERENCES snippets (id) ON DELETE CASCADE,
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by              TEXT NOT NULL,
  old_content             TEXT NOT NULL,
  -- NULL specifically means "row predates #324, the name was never captured" -- not "had no name",
  -- which is impossible since snippets.name is NOT NULL. Rows written before the snapshot widening
  -- (including everything the legacy Prisma migration backfilled) only ever recorded content edits,
  -- so the dashboard renders these content-only rather than inventing a name/attachment diff for them.
  old_name                TEXT,
  old_attachment_url      TEXT,
  old_attachment_filename TEXT
);

CREATE INDEX snippet_updates_snippet_id_idx ON snippet_updates (snippet_id);

-- Social (#343, leveling + social interactions — see docs/roadmap/10-social-port.md).
--
-- Reproduces the 6 models from `ChatSift/Social`'s `prisma/schema.prisma` (GuildSettings, Reward, User,
-- Channel, Role, SocialInteraction). Every table is `social_`-prefixed, following AMA's `ama_*`
-- (ModMail's unprefixed `guild_settings`/`threads` are grandfathered, not a pattern — and
-- `guild_settings` is literally taken).
--
-- The four deviations from legacy, collected here because the P5 migration script
-- (`migrateLegacySocial.ts`) has to account for every one of them; each is also documented at the
-- column it affects:
--   1. `level_up_notification_mode` values are uppercased to match this schema's other enum
--      (`ama_question_state`): None -> NONE, DM -> DM, Channel -> CHANNEL.
--   2. `social_channels.multiplier`/`social_roles.multiplier` are NOT NULL DEFAULT 1. Legacy's
--      `Int? @default(1)` was nullable, but a NULL there meant exactly 1 (every read site did
--      `multiplier ?? 1`), so the migration coalesces NULL -> 1 and nothing changes semantically.
--   3. `social_interactions` gets a surrogate `id` and a nullable `command_id` (see that table).
--   4. Composite primary keys are guild-first, where legacy's were (thing, guild) — see
--      `social_users`.
--
-- Bounds: legacy enforced its config bounds (required-messages 1-15, timespan 1-60s, xp-gain >= 1,
-- required-xp-base 1-500, required-xp-multiplier 1-100, channel multiplier 1-10) only in slash-command
-- option definitions, so they were never true of the data — only of writes made through the current
-- version of the bot. Those bounds live in services/api's zod schemas (P2), not here; the only CHECKs
-- below are the ones a bad value would actually break something with, since a CHECK legacy data can
-- violate is a migration that fails on prod rows.

-- Legacy's `LevelUpNotificationMode` (None/DM/Channel), uppercased per deviation 1 above.
CREATE TYPE social_level_up_notification_mode AS ENUM (
  'NONE',
  'DM',
  'CHANNEL'
);

CREATE TABLE social_guild_settings (
  guild_id                                  TEXT PRIMARY KEY,
  -- These three are legacy's "is this guild configured at all" gate: the bot is fully inert in a guild
  -- until `required_messages`, `required_messages_timespan` and `xp_gain` are all non-NULL. Deliberately
  -- nullable rather than defaulted -- "row exists, not fully configured yet" is a real state the
  -- dashboard flow needs to render, and defaulting them would silently switch XP tracking on for a guild
  -- that only ever touched, say, the notification message.
  --
  -- `required_messages` messages within `required_messages_timespan` seconds earn XP once; the rolling
  -- window itself lives in Redis (`leveling_tracking:`/`leveling_ineligible:` keys), never here.
  required_messages                         INTEGER,
  -- Seconds.
  required_messages_timespan                INTEGER,
  xp_gain                                   INTEGER,
  -- XP curve: total XP required for level n is `required_xp_base + required_xp_multiplier * n(n-1)/2`
  -- (closed form of the triangular series). This formula is frozen for migration fidelity -- changing it
  -- silently re-levels every migrated user.
  required_xp_base                          INTEGER,
  required_xp_multiplier                    INTEGER,
  level_up_notification_mode                social_level_up_notification_mode NOT NULL DEFAULT 'NONE',
  -- Where a 'CHANNEL' notification goes when the message's own channel can't be posted in. The bot
  -- nulls this itself when the fallback turns out to be dead (ported legacy behavior).
  level_up_notification_fallback_channel_id TEXT,
  -- Template supporting `{{ username }}`, `{{ level }}`, `{{ guildName }}` and `{{ earnedRewards }}`.
  -- NULL falls back to the default at render time rather than being baked in here, so the default can
  -- change later without a data migration (same reasoning as `guild_settings.anon_reply_label`).
  level_up_notification_message             TEXT,

  -- Not style bounds: level derivation walks levels upward while the accumulated requirement is still
  -- covered by the user's XP, so a base of 0 (with any multiplier) or a multiplier of 0 makes the
  -- requirement stop growing and the walk never terminate. Legacy's own command options already
  -- enforced both minimums, so real data satisfies these; a row that doesn't is one that would hang the
  -- bot, and failing the migration loudly on it is the correct outcome.
  CONSTRAINT social_guild_settings_required_xp_base_check
    CHECK (required_xp_base IS NULL OR required_xp_base >= 1),
  CONSTRAINT social_guild_settings_required_xp_multiplier_check
    CHECK (required_xp_multiplier IS NULL OR required_xp_multiplier >= 1)
);

-- Per-guild XP ledger. Guild-first PK (deviation 4): legacy's `@@id([userId, guildId])` order was
-- arbitrary -- every lookup is equality on both -- but guild-first additionally serves guild-scoped
-- scans (the migration's per-guild XP-sum verification, and the leaderboard that redesign ledger item 5
-- leaves as a follow-up). Same reasoning applies to `social_channels`/`social_roles`/`social_rewards`
-- below. No `(guild_id, xp DESC)` index yet -- `xp` is written on a hot path (every XP grant) and
-- nothing reads it in rank order until that leaderboard actually exists.
CREATE TABLE social_users (
  guild_id TEXT NOT NULL,
  user_id  TEXT NOT NULL,
  -- Total XP, with no regard for level calculations -- a level is always derived from this through the
  -- curve above, never stored. INTEGER rather than BIGINT deliberately: postgres.js hands int8 back as a
  -- string (it doesn't fit a JS number), and no plausible amount of XP approaches int4's ceiling.
  xp       INTEGER NOT NULL DEFAULT 0,
  -- Per-user opt-out: this user earns no XP in this guild.
  ignored  BOOLEAN NOT NULL DEFAULT false,

  PRIMARY KEY (guild_id, user_id)
);

-- A row here can describe the message's own channel, its parent category, or (for a thread) the thread
-- parent's parent -- the bot resolves both `ignored` and `multiplier` by walking that chain, which is
-- what lets one row silence or boost an entire category.
CREATE TABLE social_channels (
  guild_id   TEXT NOT NULL,
  channel_id TEXT NOT NULL,
  ignored    BOOLEAN NOT NULL DEFAULT false,
  -- NOT NULL DEFAULT 1 (deviation 2). Multiplies the guild's `xp_gain`; stays integral per redesign
  -- ledger item 4 (fractional multipliers change hot-path XP math and are out of port scope).
  multiplier INTEGER NOT NULL DEFAULT 1,

  PRIMARY KEY (guild_id, channel_id),
  CONSTRAINT social_channels_multiplier_check CHECK (multiplier >= 1)
);

-- Role multipliers stack multiplicatively across every configured role the member holds, on top of the
-- channel multiplier.
CREATE TABLE social_roles (
  guild_id   TEXT NOT NULL,
  role_id    TEXT NOT NULL,
  -- NOT NULL DEFAULT 1 (deviation 2), same as `social_channels.multiplier`.
  multiplier INTEGER NOT NULL DEFAULT 1,

  PRIMARY KEY (guild_id, role_id),
  CONSTRAINT social_roles_multiplier_check CHECK (multiplier >= 1)
);

-- Role rewards. One row per rewarded role, so a role can only be a reward for a single level in a guild
-- (legacy's `/reward create` was an upsert per role for exactly this reason).
CREATE TABLE social_rewards (
  guild_id TEXT NOT NULL,
  role_id  TEXT NOT NULL,
  level    INTEGER NOT NULL,
  -- A "clean"/tiered reward: only the *highest* clean reward at or below the member's level is held, so
  -- a new tier replaces the previous one. Non-clean rewards simply accumulate. The bot computes both
  -- sets additively (which roles to add, which superseded clean tiers to remove) rather than rebuilding
  -- the member's whole role set the way legacy did -- see redesign ledger item 2.
  clean    BOOLEAN NOT NULL DEFAULT false,

  PRIMARY KEY (guild_id, role_id),
  CONSTRAINT social_rewards_level_check CHECK (level >= 0)
);

-- Custom per-guild commands (`/hug`-style): each row is backed by a real Discord guild application
-- command named after it, and renders this stored content when invoked.
--
-- Deviation 3, both halves. The surrogate `id`: legacy keyed these `@@id([guildId, name])`, which makes
-- a rename an identity change and gives the dashboard's edit/delete routes nothing stable to address --
-- the same shape `snippets` (its closest analogue in this schema, down to the `command_id`) already
-- solved with an identity PK plus a `(guild_id, name)` UNIQUE. That UNIQUE also keeps the property the
-- natural key gave the migration: an accidental re-run fails loudly instead of duplicating rows.
CREATE TABLE social_interactions (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id       TEXT NOT NULL,
  -- The guild command this interaction dispatches from. Nullable, where legacy had it NOT NULL (and in
  -- its PK): a command id belongs to an *application*, so every legacy id 404s under the new bot's
  -- application. The migration writes NULL here and the P6 cutover resync assigns real ids -- the exact
  -- lesson ModMail's snippets taught (docs/roadmap/01-architecture.md §8). Dispatch tolerates a stale or
  -- missing id anyway, falling back to a `(guild_id, name)` lookup on the invoked command's name before
  -- declaring the interaction gone. See redesign ledger item 3.
  command_id     TEXT,
  -- Doubles as the Discord command name, hence the guild-wide uniqueness below.
  name           TEXT NOT NULL,
  -- Templated with `{{ author }}` and `{{ targets }}` (the latter only meaningful when `allow_targets`).
  content        TEXT NOT NULL,
  -- Embed color, kept as the string legacy stored rather than the integer Discord wants -- parsing is
  -- the renderer's job, and reinterpreting it here would need a data migration to be sure of the format.
  color          TEXT,
  -- Sent outside the embed, alongside it, when `embed` is on.
  plain_content  TEXT,
  -- Rendered as the embed's image.
  attachment_url TEXT,
  uses           INTEGER NOT NULL DEFAULT 0,
  embed          BOOLEAN NOT NULL DEFAULT false,
  -- Whether the generated command takes user-mention options, which render into `{{ targets }}`.
  allow_targets  BOOLEAN NOT NULL DEFAULT false,

  CONSTRAINT social_interactions_guild_id_name_key UNIQUE (guild_id, name)
);

-- Dispatch's primary lookup. Partial because a row with no command id is only reachable through the
-- `(guild_id, name)` fallback (covered by the UNIQUE above) until a resync gives it one -- which,
-- immediately post-migration, is every row.
CREATE INDEX social_interactions_guild_id_command_id_idx ON social_interactions (guild_id, command_id)
  WHERE command_id IS NOT NULL;
