-- Declarative schema (source of truth for `atlas migrate diff`).
--
-- Naming convention: snake_case tables/columns, mapped to camelCase JS via the
-- `postgres.camel` transform passed to `createDb()` (SimplyChords' convention —
-- see docs/roadmap/02-foundation.md Part A step 2 for the decision writeup).
--
-- Reproduces the 6 current Prisma models 1:1 (see prisma/schema.prisma and
-- docs/roadmap/01-architecture.md §5): Experiment, ExperimentOverride,
-- DashboardGrant, AMASession, AMAPromptData, AMAQuestion (+ AMAQuestionState).
--
-- Note: Prisma's `@updatedAt` on AMAQuestion.updatedAt was a Prisma-client-side
-- behavior (set on every client `.update()` call), not a DB trigger. There is no
-- trigger reproducing it here — the route migration (raw SQL, see #128) is
-- responsible for setting `updated_at = now()` explicitly on updates.

CREATE TABLE experiments (
  name        TEXT PRIMARY KEY,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ,
  range_start INTEGER NOT NULL,
  range_end   INTEGER NOT NULL
);

CREATE TABLE experiment_overrides (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id        TEXT NOT NULL,
  experiment_name TEXT NOT NULL REFERENCES experiments (name) ON DELETE CASCADE,

  CONSTRAINT experiment_overrides_guild_id_experiment_name_key UNIQUE (guild_id, experiment_name)
);

CREATE INDEX experiment_overrides_experiment_name_idx ON experiment_overrides (experiment_name);

CREATE TABLE dashboard_grants (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id       TEXT NOT NULL,
  user_id        TEXT NOT NULL,
  created_by_id  TEXT NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT dashboard_grants_guild_id_user_id_key UNIQUE (guild_id, user_id)
);

CREATE TABLE ama_sessions (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id                 TEXT NOT NULL,
  mod_queue_id             TEXT,
  flagged_queue_id         TEXT,
  guest_queue_id           TEXT,
  title                    TEXT NOT NULL,
  answers_channel_id       TEXT NOT NULL,
  prompt_channel_id        TEXT NOT NULL,
  allowed_question_uploads INTEGER NOT NULL DEFAULT 2,
  ended                    BOOLEAN NOT NULL DEFAULT false,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE ama_prompt_data (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ama_id            INTEGER NOT NULL UNIQUE REFERENCES ama_sessions (id) ON DELETE CASCADE,
  prompt_message_id TEXT NOT NULL UNIQUE,
  prompt_json_data  TEXT NOT NULL
);

CREATE TYPE ama_question_state AS ENUM (
  'PENDING_MOD_REVIEW',
  'PENDING_GUEST_REVIEW',
  'FLAGGED',
  'APPROVED',
  'DENIED'
);

CREATE TABLE ama_questions (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ama_id                   INTEGER NOT NULL REFERENCES ama_sessions (id) ON DELETE CASCADE,
  author_id                TEXT NOT NULL,
  state                    ama_question_state NOT NULL DEFAULT 'PENDING_MOD_REVIEW',
  content                  TEXT NOT NULL,
  mod_queue_message_id     TEXT,
  guest_queue_message_id   TEXT,
  flagged_queue_message_id TEXT,
  answers_message_id       TEXT,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ama_questions_ama_id_idx ON ama_questions (ama_id);

-- ModMail (M5, ticket-system rebuild — see docs/roadmap/06-modmail-port.md and issue #152).
--
-- Reproduces the 9 carried-forward models from `ChatSift/ModMail`'s `prisma/schema.prisma`
-- (GuildSettings, Snippet, SnippetUpdates, Thread, ThreadMessage, ScheduledThreadClose, Block,
-- ThreadOpenAlert, ThreadReplyAlert), mostly 1:1, plus two new models (Category, TicketPanel)
-- and a join table (TicketPanelCategory) for the new create-flow.
--
-- Design decisions confirmed 2026-07-23 (owner sign-off, see issue #152 discussion) that shape
-- this section:
--   - Category routing is forum-tag-only: every guild has a single mod forum
--     (guild_settings.mod_forum_id); categories map to a tag within it (categories.forum_tag_id),
--     not a separate forum channel per category.
--   - No staff-role concept was added. The mention/user-ID auto-embed QOL feature (bot-side, not
--     a schema concern) only fires on relayed *user* messages, never staff replies — decided by
--     checking thread_messages.staff_id/user_id on the message being relayed, not by a role.
--   - Multiple ticket panels per guild are expected, each scoped to a subset of a guild's
--     categories chosen at panel-creation time — hence ticket_panel_categories.
--
-- threads.channel_id (old Prisma model) is renamed to mod_thread_id here, disambiguating it from
-- the new user_thread_id now that a thread has two Discord-thread concepts (mod-forum side vs.
-- the user's private thread). Free to do since this table has no prior rows in the new schema.

CREATE TABLE guild_settings (
  guild_id                 TEXT PRIMARY KEY,
  mod_forum_id             TEXT,
  default_greeting_message TEXT,
  farewell_message         TEXT,
  simple_mode              BOOLEAN NOT NULL DEFAULT false,
  alert_role_id            TEXT
);

CREATE TABLE categories (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id         TEXT NOT NULL,
  name             TEXT NOT NULL,
  emoji            TEXT,
  description      TEXT,
  greeting_message TEXT,
  forum_tag_id     TEXT,
  sort_order       INTEGER NOT NULL DEFAULT 0,

  CONSTRAINT categories_guild_id_name_key UNIQUE (guild_id, name)
);

CREATE INDEX categories_guild_id_idx ON categories (guild_id);

-- Tag-based routing (see comment above) is ambiguous if two categories in the same guild share a
-- forum tag; partial (forum_tag_id nullable, since a category can be unconfigured) unique index
-- enforces one category per tag per guild.
CREATE UNIQUE INDEX categories_guild_id_forum_tag_id_key ON categories (guild_id, forum_tag_id) WHERE forum_tag_id IS NOT NULL;

CREATE TABLE ticket_panels (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id        TEXT NOT NULL,
  channel_id      TEXT NOT NULL,
  message_id      TEXT NOT NULL UNIQUE,
  panel_json_data TEXT NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ticket_panels_guild_id_idx ON ticket_panels (guild_id);

CREATE TABLE ticket_panel_categories (
  ticket_panel_id INTEGER NOT NULL REFERENCES ticket_panels (id) ON DELETE CASCADE,
  category_id     INTEGER NOT NULL REFERENCES categories (id) ON DELETE CASCADE,

  PRIMARY KEY (ticket_panel_id, category_id)
);

CREATE INDEX ticket_panel_categories_category_id_idx ON ticket_panel_categories (category_id);

CREATE TABLE threads (
  id                            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id                      TEXT NOT NULL,
  mod_thread_id                 TEXT NOT NULL,
  user_id                       TEXT NOT NULL,
  created_by_id                 TEXT NOT NULL,
  created_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
  closed_by_id                  TEXT,
  closed_at                     TIMESTAMPTZ,
  last_local_thread_message_id  INTEGER NOT NULL DEFAULT 0,
  category_id                   INTEGER REFERENCES categories (id) ON DELETE SET NULL,
  user_thread_id                TEXT
);

CREATE INDEX threads_guild_id_idx ON threads (guild_id);
CREATE INDEX threads_category_id_idx ON threads (category_id);

CREATE TABLE thread_messages (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_thread_message_id  INTEGER NOT NULL,
  guild_id                 TEXT NOT NULL,
  thread_id                INTEGER NOT NULL REFERENCES threads (id) ON DELETE CASCADE,
  user_id                  TEXT NOT NULL,
  user_message_id          TEXT NOT NULL,
  staff_id                 TEXT,
  guild_message_id         TEXT NOT NULL,
  anon                     BOOLEAN NOT NULL DEFAULT false,

  CONSTRAINT thread_messages_thread_id_local_thread_message_id_key UNIQUE (thread_id, local_thread_message_id)
);

CREATE INDEX thread_messages_thread_id_idx ON thread_messages (thread_id);

CREATE TABLE scheduled_thread_closes (
  thread_id       INTEGER PRIMARY KEY REFERENCES threads (id) ON DELETE CASCADE,
  scheduled_by_id TEXT NOT NULL,
  silent          BOOLEAN NOT NULL DEFAULT false,
  close_at        TIMESTAMPTZ NOT NULL
);

CREATE TABLE blocks (
  user_id    TEXT NOT NULL,
  guild_id   TEXT NOT NULL,
  expires_at TIMESTAMPTZ,

  PRIMARY KEY (user_id, guild_id)
);

CREATE TABLE thread_open_alerts (
  guild_id TEXT NOT NULL,
  user_id  TEXT NOT NULL,

  PRIMARY KEY (guild_id, user_id)
);

CREATE TABLE thread_reply_alerts (
  thread_id INTEGER NOT NULL REFERENCES threads (id) ON DELETE CASCADE,
  user_id   TEXT NOT NULL,

  PRIMARY KEY (thread_id, user_id)
);

-- Note: Prisma's `@updatedAt` on Snippet.lastUpdatedAt was client-side (set on every `.update()`
-- call), not a DB trigger — same caveat as AMAQuestion.updatedAt above. Whatever route/service
-- code updates a snippet's content is responsible for setting `last_updated_at = now()` itself.
CREATE TABLE snippets (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id        TEXT NOT NULL,
  command_id      TEXT NOT NULL,
  created_by_id   TEXT NOT NULL,
  name            TEXT NOT NULL,
  content         TEXT NOT NULL,
  times_used      INTEGER NOT NULL DEFAULT 0,
  last_used_at    TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT snippets_guild_id_name_key UNIQUE (guild_id, name)
);

CREATE TABLE snippet_updates (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snippet_id  INTEGER NOT NULL REFERENCES snippets (id) ON DELETE CASCADE,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by  TEXT NOT NULL,
  old_content TEXT NOT NULL
);

CREATE INDEX snippet_updates_snippet_id_idx ON snippet_updates (snippet_id);
