-- One-off: fold the `prod` deployment's database into the surviving (canary) one.
--
-- Context: two deployments have been running side by side since the M4 cutover -- `chatsift-prod`
-- (branch `prod`, public @AMA#5595, AMA only) and `chatsift-v3` (branch `main`, canary AMA +
-- ModMail + Social). The canary one survives and adopts the public AMA token; this script moves
-- prod's rows into it. See docs/prod-branch.md §Convergence on the `prod` branch for why that
-- direction was chosen.
--
-- Unlike scripts/import-legacy-ama.mjs and scripts/copy-ama-session.mjs, this is plain SQL rather
-- than a generator: both databases run the *same* schema here (identical migration set), so the
-- move is an INSERT ... SELECT across two schemas in one database and never needs SQL literals
-- built in JS. That also means no quoting/escaping surface -- question text, snippet bodies and
-- prompt JSON travel as CSV through psql's \copy and are never re-serialized.
--
-- Prerequisite: prod's rows have been loaded into a `prod_import` schema in THIS database (the
-- runbook's Step 3). Run this file with:
--   ./compose exec -T postgres psql -U chatsift -d chatsift -v ON_ERROR_STOP=1 -f - < merge-prod-into-canary.sql
--
-- Everything below runs in one transaction. The temp tables are ON COMMIT DROP, so a failure
-- anywhere leaves the database exactly as it was.

BEGIN;

-- ---------------------------------------------------------------------------------------------
-- 1. Sessions that must NOT be copied.
--
-- One AMA (the one originally brought over from legacy `ChatSift/AMA` by import-legacy-ama.mjs)
-- was copied canary -> prod by copy-ama-session.mjs. Its original row is still in this database,
-- so re-importing prod's copy would duplicate it. That script carries `share_token` over verbatim,
-- which makes the copy exactly identifiable -- no guesswork, no id matching.
--
-- Belt and braces: `ama_prompt_data.prompt_message_id` is also carried verbatim and is UNIQUE, so
-- even if this filter were wrong the insert below would abort rather than silently duplicate.
-- ---------------------------------------------------------------------------------------------
CREATE TEMP TABLE _skipped ON COMMIT DROP AS
SELECT src.id AS src_id, src.title, src.share_token, dst.id AS existing_id
FROM prod_import.ama_sessions src
JOIN public.ama_sessions dst ON dst.share_token = src.share_token;

CREATE TEMP TABLE _sessions ON COMMIT DROP AS
SELECT src.*
FROM prod_import.ama_sessions src
WHERE NOT EXISTS (SELECT 1 FROM _skipped sk WHERE sk.src_id = src.id);

-- ---------------------------------------------------------------------------------------------
-- 2. Per-table id offsets.
--
-- Every AMA table keys on INTEGER GENERATED BY DEFAULT AS IDENTITY, so both databases number from
-- 1 and every id collides. GENERATED BY DEFAULT (rather than ALWAYS) is what makes this tractable:
-- explicit ids insert without disabling anything. Each source id is shifted above this database's
-- current max for that table, and every FK referencing it is shifted by the same amount.
-- ---------------------------------------------------------------------------------------------
CREATE TEMP TABLE _offsets ON COMMIT DROP AS
SELECT
	(SELECT coalesce(max(id), 0) FROM public.ama_sessions)        AS session_off,
	(SELECT coalesce(max(id), 0) FROM public.ama_prompt_data)     AS prompt_off,
	(SELECT coalesce(max(id), 0) FROM public.ama_questions)       AS question_off,
	(SELECT coalesce(max(id), 0) FROM public.ama_question_askers) AS asker_off,
	(SELECT coalesce(max(id), 0) FROM public.ama_question_tags)   AS tag_off,
	(SELECT coalesce(max(id), 0) FROM public.dashboard_grants)    AS grant_off;

-- ---------------------------------------------------------------------------------------------
-- 3. Insert parent-first, following the FK graph.
--
-- Discord message ids (queue_message_id / answers_message_id / prompt_message_id) are carried over
-- verbatim, which is the opposite of copy-ama-session.mjs's default. That script nulls them because
-- it moves rows *between* bot applications, and Discord won't let one application edit another's
-- messages. Here the surviving deployment adopts prod's own token, so these ids keep pointing at
-- messages it can still edit. (The reverse now applies to this database's pre-existing canary-authored
-- rows -- see the runbook's "known one-way costs".)
-- ---------------------------------------------------------------------------------------------
INSERT INTO public.ama_sessions (
	id, guild_id, queue_id, title, answers_channel_id, prompt_channel_id,
	allowed_question_uploads, ended, scheduled_close_at, prepared_answers_enabled,
	review_enabled, share_token, guest_ids, created_at
)
SELECT
	s.id + o.session_off, s.guild_id, s.queue_id, s.title, s.answers_channel_id, s.prompt_channel_id,
	s.allowed_question_uploads, s.ended, s.scheduled_close_at, s.prepared_answers_enabled,
	s.review_enabled, s.share_token, s.guest_ids, s.created_at
FROM _sessions s
CROSS JOIN _offsets o;

INSERT INTO public.ama_prompt_data (id, ama_id, prompt_message_id, prompt_json_data)
SELECT p.id + o.prompt_off, p.ama_id + o.session_off, p.prompt_message_id, p.prompt_json_data
FROM prod_import.ama_prompt_data p
JOIN _sessions s ON s.id = p.ama_id
CROSS JOIN _offsets o;

INSERT INTO public.ama_question_tags (id, ama_id, name, created_at)
SELECT t.id + o.tag_off, t.ama_id + o.session_off, t.name, t.created_at
FROM prod_import.ama_question_tags t
JOIN _sessions s ON s.id = t.ama_id
CROSS JOIN _offsets o;

INSERT INTO public.ama_questions (
	id, ama_id, author_id, state, content, queue_message_id, answers_message_id,
	answer_content, answer_image_url, answered_by_id, answered_at, asked_at, created_at, updated_at
)
SELECT
	q.id + o.question_off, q.ama_id + o.session_off, q.author_id, q.state, q.content,
	q.queue_message_id, q.answers_message_id, q.answer_content, q.answer_image_url,
	q.answered_by_id, q.answered_at, q.asked_at, q.created_at, q.updated_at
FROM prod_import.ama_questions q
JOIN _sessions s ON s.id = q.ama_id
CROSS JOIN _offsets o;

INSERT INTO public.ama_question_askers (id, question_id, author_id, content, merged_at)
SELECT a.id + o.asker_off, a.question_id + o.question_off, a.author_id, a.content, a.merged_at
FROM prod_import.ama_question_askers a
JOIN prod_import.ama_questions q ON q.id = a.question_id
JOIN _sessions s ON s.id = q.ama_id
CROSS JOIN _offsets o;

INSERT INTO public.ama_question_tag_assignments (question_id, tag_id, ama_id)
SELECT ta.question_id + o.question_off, ta.tag_id + o.tag_off, ta.ama_id + o.session_off
FROM prod_import.ama_question_tag_assignments ta
JOIN _sessions s ON s.id = ta.ama_id
CROSS JOIN _offsets o;

-- Dashboard access is per (guild, user) and both deployments served the same dashboard product, so a
-- user who managed a guild on both sides already has a row here. ON CONFLICT DO NOTHING keeps this
-- deployment's own grant (same meaning either way -- the row carries no state beyond its existence).
INSERT INTO public.dashboard_grants (id, guild_id, user_id, created_by_id, created_at)
SELECT g.id + o.grant_off, g.guild_id, g.user_id, g.created_by_id, g.created_at
FROM prod_import.dashboard_grants g
CROSS JOIN _offsets o
ON CONFLICT (guild_id, user_id) DO NOTHING;

-- ---------------------------------------------------------------------------------------------
-- 4. Resync the identity sequences past the ids just inserted.
--
-- Without this the next INSERT reuses an id that now exists and fails on the primary key. The
-- three-argument setval form handles a table that is still empty on both sides: is_called = false
-- means the next value handed out is 1 rather than 2.
-- ---------------------------------------------------------------------------------------------
SELECT setval(pg_get_serial_sequence('public.ama_sessions', 'id'),
	coalesce(max(id), 1), max(id) IS NOT NULL) FROM public.ama_sessions;
SELECT setval(pg_get_serial_sequence('public.ama_prompt_data', 'id'),
	coalesce(max(id), 1), max(id) IS NOT NULL) FROM public.ama_prompt_data;
SELECT setval(pg_get_serial_sequence('public.ama_questions', 'id'),
	coalesce(max(id), 1), max(id) IS NOT NULL) FROM public.ama_questions;
SELECT setval(pg_get_serial_sequence('public.ama_question_askers', 'id'),
	coalesce(max(id), 1), max(id) IS NOT NULL) FROM public.ama_question_askers;
SELECT setval(pg_get_serial_sequence('public.ama_question_tags', 'id'),
	coalesce(max(id), 1), max(id) IS NOT NULL) FROM public.ama_question_tags;
SELECT setval(pg_get_serial_sequence('public.dashboard_grants', 'id'),
	coalesce(max(id), 1), max(id) IS NOT NULL) FROM public.dashboard_grants;

-- ---------------------------------------------------------------------------------------------
-- 5. Report, inside the transaction, so an unexpected number can still be rolled back.
-- ---------------------------------------------------------------------------------------------
DO $merge_report$
DECLARE
	r RECORD;
	skipped INTEGER;
BEGIN
	SELECT count(*) INTO skipped FROM _skipped;

	FOR r IN SELECT src_id, title, existing_id FROM _skipped LOOP
		RAISE NOTICE 'SKIPPED already-present session: prod id % (%) is already here as id %',
			r.src_id, r.title, r.existing_id;
	END LOOP;

	RAISE NOTICE 'Merged % session(s) (% skipped), % question(s), % tag(s), % assignment(s), % asker(s), % grant(s) considered.',
		(SELECT count(*) FROM _sessions),
		skipped,
		(SELECT count(*) FROM prod_import.ama_questions q JOIN _sessions s ON s.id = q.ama_id),
		(SELECT count(*) FROM prod_import.ama_question_tags t JOIN _sessions s ON s.id = t.ama_id),
		(SELECT count(*) FROM prod_import.ama_question_tag_assignments a JOIN _sessions s ON s.id = a.ama_id),
		(SELECT count(*) FROM prod_import.ama_question_askers a
			JOIN prod_import.ama_questions q ON q.id = a.question_id
			JOIN _sessions s ON s.id = q.ama_id),
		(SELECT count(*) FROM prod_import.dashboard_grants);

	RAISE NOTICE 'Offsets applied: %', (SELECT row_to_json(o) FROM _offsets o);
END $merge_report$;

COMMIT;
