#!/usr/bin/env bash

set -euo pipefail

git_dir="$(git rev-parse --absolute-git-dir 2>/dev/null || true)"
common_dir="$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null || true)"

# Not a repo, or the main checkout (where both point at the same .git) -- nothing to do.
if [ -z "$git_dir" ] || [ "$git_dir" = "$common_dir" ]
then
  exit 0
fi

worktree_root="$(git rev-parse --show-toplevel)"
main_root="$(dirname "$common_dir")"
slug="$(basename "$worktree_root" | tr -c 'A-Za-z0-9' '_' | sed 's/_*$//')"

cd "$worktree_root"

link_into_worktree() {
  local rel="$1"

  [ -e "$main_root/$rel" ] || return 0
  [ -h "$rel" ] && rm -f "$rel"
  [ -e "$rel" ] && return 0

  mkdir -p "$(dirname "$rel")"
  ln -s "$main_root/$rel" "$rel"
}

link_into_worktree .env.private
link_into_worktree build/prometheus/metrics_secret

mkdir -p "$main_root/.yarn/cache" "$main_root/.turbo/cache"
link_into_worktree .yarn/cache
# Only the cache, not all of .turbo: daemon/ and cookies/ are per-root state that must stay local.
link_into_worktree .turbo/cache

if [ ! -e .env.worktree ]
then
  cat > .env.worktree <<EOF
# Generated by scripts/worktree-bootstrap.sh. Gitignored, worktree-local, overrides .env.private and
# .env.public. Delete it to fall back to the shared dev database.
DATABASE_URL_DEV=postgres://chatsift:admin@127.0.0.1:\${LOCAL_DATABASE_PORT}/chatsift_wt_$slug
EOF
fi

if [ ! -d node_modules ]
then
  echo "worktree '$slug' is bootstrapped but has no node_modules -- run 'yarn install' before building."
fi
