name: Deploy next

on:
  workflow_run:
    workflows:
      - 'Quality Check'
    branches:
      - v3
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install dependencies
        uses: ./actions/yarnCache

      - name: Build the images
        run: docker build -t chatsift/chatsift-next:latest -f ./Dockerfile .

      - name: Tag changes
        run: yarn turbo run tag-docker --filter '...[HEAD~1...HEAD]'

      - name: Push to DockerHub
        run: docker push --all-tags chatsift/chatsift-next
