name: Documentation
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install pnpm
        run: curl -L https://unpkg.com/@pnpm/self-installer | node

      - name: Use node_modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install deps
        run: pnpm i

      - name: Build the code
        run: pnpm run build

      - name: Build documentation
        run: pnpm run docs

      - name: Place CNAME
        run: echo "oss-docs.automoderator.app" >| ./docs/CNAME

      - name: Commit the Docs
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'docs'
          destination-github-username: 'github-actions[bot]'
          destination-repository-username: 'chatsift'
          destination-repository-name: 'packages-docs'
          target-branch: 'main'
          user-email: 41898282+github-actions[bot]@users.noreply.github.com
