name: Quality Check

on: [push, pull_request]

jobs:
  checks:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        run: curl -L https://unpkg.com/@pnpm/self-installer | node

      - name: Use node_modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install deps
        run: pnpm i

      - name: Make sure prisma schema is up to date
        run: pnpm prisma generate

      - name: Build the code
        run: pnpm run build

      - name: Run ESLint
        run: pnpm run lint:ci

      - name: Run Jest Tests
        run: pnpm run test:ci
